---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 18.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true
    blocking:
      # --  Add blocky whitelists
      # `default` name is reservered for TrueCharts included default whitelist
      # example shows the structure, though name should be changed when used
      whitelist:
        []
        # - name: default
        #  lists:
        #   - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
        #   - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        #   - https://raw.githubusercontent.com/rahilpathan/pihole-whitelist/main/1.LowWL.txt

      # -- Blocky blacklists
      # `default` name is reservered for TrueCharts included default blacklist
      # example shows the structure, though name should be changed when used
      blacklist:
        []
        # - name: default
        #  lists:
        #   - https://big.oisd.nl/domainswild
        #   - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts    k8sgateway:
      domains:
      - domain: "${DOMAIN_0}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      - domain: "${DOMAIN_1}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
    defaultUpstreams:
    - "https://1.1.1.1/dns-query"
    bootstrapDns:
      ips: []
      upstream: "1.1.1.1"
    queryLog:
      type: ""
    configmap:
      dashboard:
        enabled: false
      datasource:
        enabled: false
    cnpg:
      main:
        enabled: false
    metrics:
      main:
        enabled: false