apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2UqymplGid39Cny9D0MQvrdcUW475ylwCTJKYfgl3InYNJ4vtrwqZQ==,iv:58I60+Bnv2fa7ojYcf4HkFbfqo0bqBtDgM0ZdzjdFpE=,tag:j38H7AMLn77K5WJ//fNaFQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cXJmNHQxRGhUemxHWTZh
            TzNJK2QvTDd4dHFPalBoNnJNb3FyOEpmVWwwClF1OUMrZEl4enNKVldUVDVPRERq
            R1dQMHBEOW9VWGFDYitacERsOFRPMk0KLS0tIDBoNWNNQkVsK2Z1WFFzVzZrQ01V
            Zk1NeEFXSEw2KytXNUxFRkMwWW5iTlEK4snKda3zRj6LekMbW/yxklhG+yGykPgA
            Guar0QshO/z2yWDOyxh+b0k60AeI0zA99VXp+zQjRqXig0MLuqZMyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T23:49:35Z"
    mac: ENC[AES256_GCM,data:g/7OQsZrVFzUO78aK3i1xan3SR6LYDM96Ju+l0TqMd0VdIgqCkutF7cl2NfxtwVy0RpjYYSypEwA2Nsn2V/lfG5BCk5RjtAskMJ+IL4rbUGKVWE9kYfYUq3ZCBHENqWzwwF5ysM9DlM4n/StoC/vasyY93ip1nnM5MnF82uKPZM=,iv:mYNOOG/n42hhlUMsfjGNlQWstbIAf6+Oi/JBfDJAjKo=,tag:ZBsE8XkmuqbGZVef0TB2Ug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
