apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Aa0PDC2sypfJTXjfgDSD+nGWILdJUVten6mgjcc8ToiAY71771XmJA==,iv:rJxGCH9n1Xl/EL/CgL+KOtRizrMDel+tGYG/Y1hImaQ=,tag:dTWcSUrTPFKIuwDpVETmgQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcFhTTjFqM1ZXbVdRcm5v
            bVN2VktSNU85RFNBclFuTFdqOUpoaFVWZ1NnCklCZC85d1lXKzlkN1NhZVRhSEgx
            VVNBQi9CUkp3K3VVSTErcmVxVkZqODgKLS0tIFNRT01DU3MvUGdjVmZaVzdiM2ds
            NGZMRUp4QjRQVzNQWitPZUJ4RWZIb00K2QISYjcIlPfRPAqsVzxR/+1nzcDEsHWT
            vCz2/GrZpT7PkLYFjissDxWXdY/rnb514t7kT3m+6Vz7CQClRD81Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T22:46:54Z"
    mac: ENC[AES256_GCM,data:KHnMyDKVp2GIkn2ySl6cwK0uAfQzVX3Sw9+ErhJQRwXuvziUfzTroIrDks7xpo5rd5PuYh2RdqfyccaPMUosbYkZvwZJjC/66TdVsJHXTbf2IKxGnqsQZuuOrkQwpklwXbqRyqDnxdJbpJxjZty9SqsBBTlHc0cWomasfemQgb4=,iv:yZkmbG6cq17biSm33s9X/ZH26W0NciRFsuZHKjayKqI=,tag:ZLUwp4Xg9lM3DChCR42xsg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
