apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2vOT5YjfcD540dMZejgVAc1esoID6acx8Pv9qhZub08yq1HbLVpraQ==,iv:fUe65c/Zf6vKcmDGMGb/vYrEhAvSa+L3G139xT8PnkM=,tag:jfWv1AS6LfaOnumQZWkMSg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUUFvdTNETnMvR2NpRGxx
            NkRBTkxycUtzd2kwQUpuOVVJUmJNczVyUzNZCjZnRFZxWU1lRXlvcC93aG9QMndo
            YTBiNDBvZXg1dWh2ZDd5cW1VMTZvdHMKLS0tIE9McWVHRENwVUY0eVdYRmNxY1BJ
            bFgrajVvOVBDMjNOKzFlNmJveEtsQU0KyV12TWBbfwc86omp6l9UpDMODjumedEH
            nmmFfZQ7GyY+el2vz5J/huUijVmeSn5mfKBUeJRAC3SgO8NbWASEgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T13:44:37Z"
    mac: ENC[AES256_GCM,data:apNktHEvObv+n5YKHY3gYQiQQIHXOA09IL0mfWMTFfRARu73mUw2hwzB2YoaNRHyty+I/FwFDSouLZlD2dOyuEuANO4cViHNGAitSqZ5I7MPr2chpy8q2qVRfyBZDH0PLQl/0PtjPlOAaOT0WB2y2lq/gBIEPbqw1lLRbDLMjiU=,iv:klSNwidliwlTHRlZIoLUqEctIVRb9/3fnT142vdevvE=,tag:8OutfIf7eQR3XX+H8bHpFQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
