apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:CWAWD0gLDYoHbytgUbz80p7TKIBY6MeTF4HcPKWwEtlCsjREXvVEqw==,iv:mLWANOtDQ+SXfo1xyOwoS/Fb9ecr1Gcz+2NtAWLCdrg=,tag:wt+sZrXd17gsB6HlpPLssg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cTVYQUJmWnpHYzlydm5u
            dDdiKzhDejlXU1pNOG9iK2RZLzFXVWt3Q2trClFRYzRtMUtCVU4vRmRnYUZ3cmJH
            M05oZWh1RUczZUN4Q1dpMXlyYStjbDQKLS0tIGtxNm9SbkJFR09PWEFTZnlwYVFM
            YkFTaEFDZDV2ZWdjc1BHM3F0MVE0cU0KsMx1jb9qLtLsiJeGhQn8ENaAseO2LFaj
            MWX/oQwZjIkg4dd9wWvxaTyOno8yC9C19M22oBkSR3jAGFaZ10MQjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:34:42Z"
    mac: ENC[AES256_GCM,data:LBqTJ0EbDWQ3p7ga1bS4zAzkwoJl3kasNcCHmm6sT8//65VeLapPtZBXArNuYldXPGy1qUVnTrypVCSWoRNzMIARE4q0BD1MkdyXaCwGurrZbMbj4M1l8h19Zm4FKh1eYrAdSKwqsSOChjap2vhYSqBTRcejnOgGuo4QUo3YZkM=,iv:rATLLQUtSTzyzqAdL2adQ8CH488h06jAGH9ffqdMZhk=,tag:bkc6l22cAxtPQjGWqBzaOg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
