apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:wm0drsM7hm3jM6KhapRwklBbww/cy0NiGSoe2P5szRJgrxtESkGKTg==,iv:rAru1TZ8rBD9D+D56CcR/Tlxa423cDWEFQ2TIJM1NlA=,tag:XSMwEgua0tkKoDaqBWMHXA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcFVWbjZHclQ4WngvNHl6
            SGdLVGN2cXhwYjRBQm85RG5kdktUMUVUdUVBCkwzeDl3ckJVMm81YjVMWUV1UmVv
            dlVML1dVdDUvbmNCUlp2NXJVcEhxZUEKLS0tIHAvZWkvYytPUjkyS1JBNktPclpz
            NWhZMTRCR2xrTnlPeU50THN6OFZMQW8K+VC53DU3pSNh1nNs/1Jtn3n8w3s1gykS
            GmYlnvVfpebWl79BFWTXpxkglEp/0x0dSNDNT6WdNqn8lHVutJtddA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T01:17:59Z"
    mac: ENC[AES256_GCM,data:lmgRS6emSnjWN0KIgWDVL9VprcfmgJ7FBIRiPw+ADet7gk20Z+w0Wc/5J4+a+I7uyAjCYNH0jN6qLDXPUT5V8/ZgTOVzr1HkQuVz/jstjQA3CPVVCGXZvcU/141ckTEmT4P5PnMWpG+QNFnE8eUD3NzS1CSeQKQJ2ZECPnFLsOw=,iv:HfuIvch7Ni185xPOk413fmWjjD9xmEg6ZMDG0Tx1I7c=,tag:HjrGFiEl70wTxLTOYKY5jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
