apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/N2JtC9UJMcrkD361bSqM2IkpeDN80J7XUDQ/BPEe7MjBrbDFkNQ5g==,iv:7pY2S8q1W5yfG/rHfOOIGrbig8abDn+Gaq82KUMMz9w=,tag:SkCdSLz2nmdpkjFOmFPv1w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT2dva2w5WHlCUGlFbFVH
            MXZnNlR3UE84YTcwZks1bDNicVJaOGJLdlZVCjdGem9ZdVpvQ0NrWFZtWUNwazZO
            L05FTnNzSE0xVjhZZUo2N3lPeHBBR2cKLS0tIEFxMHB0NlplNldzeWYyM1UvY1BM
            VG5KeHhOMWEvclE3NVFXN3BOdnZ6dUUK864UKiyp5nwCM6iB2EgSHBckun38MoYF
            GaVX+7bILD3xn0DbDch55SvPcfP+IzRe2M+wnKkPNQ+urpnnpcyI4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T03:59:48Z"
    mac: ENC[AES256_GCM,data:b9ixH6xNy6QfikM5qaVPO8593K7MX3zxzZF4HWf4xnw9gyZprBmu1EvVRQqpTa1Y/SVCJmPCPGRg03Y3iHwdfqcvoyDeBydyRm19zAg+v1won4EQyVclqfql9ASr6+jzqBpkF6tm3MVPeSVkCcnI58RKIsOKu5/0IGRqvPsMXRs=,iv:VFmDM1PR1Cbin6UIPGy52a4V4yWZrWdU2j6EFJnOVK0=,tag:4LPhNAdpz1Xac2MHjifq+w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
