apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EYA5bu9xKK5fXfV69qxWRoj9+M0YNDwC9S4u4wNyy605JUC4vuNp3A==,iv:qW6mCZHX0o1t8yIsLNkakOthVY/DrznTrq12vA+qLzc=,tag:hyrN5SLuxnIfk9N4+dKQbw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jca0kv92mk3n60mwnrf2uwlpsgyt48uz66tudq6g7ud5uuar84tsq8s49a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNThmbFlWWFNjb3RBS0t2
            QVdDUDhCTkt1MGg3c3RLdXNYbUZCYnpTeXpzCkxIRVVBRHR4aXFtczNPZ3NDbnI4
            UG14Mm1oOTF0MUtkZ3BNSytuOGxGNzAKLS0tIEdpMFBWOU9JUTdtMkF4QldxNzZo
            Yjh3Z09McGdBQWY2SVlTUjd2QXMxMWsK/gnIPwW4dKFaPi77vNEkl9vBqgZun+4H
            AEap2mPk+aNqH815spygU7d+yoG7mxVeLmTspafdblSNbjZyD0xLGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T00:11:03Z"
    mac: ENC[AES256_GCM,data:jrUvSz3lAkpHugoqsiTYYaDgsbf8Q/tJ2rLX8OAn0LwY5LgDihPsQZRVJR96ADujNf16o6/Zg/J+v1FO62Wj4z7qOQ1NNgGxIrqzZ7DGa7EURcRjFyBPLt7QrOKEUXXDf/Aq9co40pvy5YuJZy8VkHKOI1xJkg1Z5lS4cFkJdUg=,iv:rCwwX0A8VMJzxYYu+gV2IuICjCaee06JDSCy3TQhung=,tag:mEgR9Xt95K/Efl9Eq+MupA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
