apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eJeofvpsj9AzA6L5DF7bCppA112Md8llI4jRKu8s0t7cT0ebom3rAg==,iv:ngJKf4a1y31MsiONb0gYZZA03Dt2fxnagrtHlfWzrnI=,tag:pK4DEb2MBIvhBhqM3S1RTA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbnFFbVBCMHdTbVZwQjRn
            TlNyaGg5L3NOWm8xWTFYL2NJOE8xbXg4aHpBCmtDU0lxWllyK294SFEvWmtxakh5
            bXVwR2k0V0QvVE1PZENyUUJCZ1BlYmcKLS0tIG1zcXM3SWFQaU1oOFZhaDVRTjNJ
            UzgrVWdIOW9kNnVmMjl5akdiSUpBMlkKN4kIMhwK5/xhCGF95nPTeMxUvhvhojNu
            myu4BQrsVtwdTHEiPRltAnQMrKciSVS61XEya3xJmJDY+hcjakB6Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T00:56:13Z"
    mac: ENC[AES256_GCM,data:AuLXQK0rD8k3ajd2z8nOEamDxYqUcLDCaV/zPFXFZqENJ4koD0NIm8hDHSm0AxajlqVuL8lqTD1AyCXjNjn/wFCUlkwgpAHE8MWgDRbUu/2tnIoiDvN3fNwY7J4PEASpcRkF/ZUE7k6t70SEbE9c4ox7a6cqgzXaU1O0ky++i8s=,iv:62jpdgp4KOzg79Tnxbvm01EepUH2gF3rGuJO0kjlQ8E=,tag:HnENYDpcXzsRMJR/hhG8/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
