apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:G0km7gVpBc8s2V4chmQpmFi14uCZxWyAlhy8FX0exKhWptLMKj7V1w==,iv:ulVWSOZqrtSCvHgT4R5P25igJ7cqBjtEcvYVvrJoaUs=,tag:BX73iwKCT8ML+7/Q2DIvNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSlF1a013am9ieW9rQW0x
            L3VrUFJLUmZ4Q1dpNGRSZ3RGakxvUy9GS1JzCkIvWnlkL29wckpwZVpLUlNXQ1Y0
            dVFlNmVJR2hSbTloN3hxVUVuV1ZBWUEKLS0tIHBuSHptV2lyZ2oySWhHcDMvQnlK
            M3ZhRjk1SWdLbTIrdFZXdFpWbG14azQKdXF4VjwgPS+eXw/RJnv+z7Qmdr1j8ye+
            KRpMuJSQ6U8jiocHi1wqovf55hzXkaLkWqTn7L1+m3xlUPwfEQOuFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:58:09Z"
    mac: ENC[AES256_GCM,data:KV7hjWMqMaa+XTF1TCKQwoE9dM6/7e8gMQnPVeHwsuBVSzWyH/ViTfpFDcAFgaaIGNFgOmlITqbtCGsl8cknUQjKY4ByRwOOP8bu91mBSeVdrPFJNs1oILu/Cvb9nX8h5glzvfuHZN8EyN/p/xhFXOggGak/IFS4e1imBB24PGs=,iv:JRjAE5C2n/ttNuLe7SAc7qV1t8P0v/lVyvbsBxcZTRQ=,tag:CNadPhGJO/aMvxz94PsaUA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
