apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2+70WiPqNJCiPeCs8Uo07QBl8Rx4tHG3gZaOd1F7cVKosMPU7VdSog==,iv:XSVDxtaCmDcPlILAdpl0F6JNgVGvtvIXnn6asEN4KfE=,tag:Mq1/Ffx+E28I+v+T4/Gvvw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jca0kv92mk3n60mwnrf2uwlpsgyt48uz66tudq6g7ud5uuar84tsq8s49a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQkV6UEw1Q0s3ZEpZRThT
            TmNIVU9Ub25ZUURKbjZaeHZNcHZlMDVvTVZRClpuTThmUTE4Y3ZLbEk1bWJZS092
            YVZJVXB2T3NtUXllQ2xOZ29kZ2QvazQKLS0tIG1KMGVoazdqeWM3aHh0S2RWbUNY
            YXd1NzBjTGxRa01nN242VlVvRTRaOGcKSUtItPoH4LMap3MaeZ8cVxUQDnmYk2LA
            eQlzaXbrH5qZKwKjTVOaLxCBvn9DMqJ8vdLr5iYZALtNW/Fqx73XEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T23:46:21Z"
    mac: ENC[AES256_GCM,data:I5eJjW+AVK+qfHYyP7uBAL23AXoQnn8wHtvvgw9ZyqLrcyZLvt8I7KUdnGLK1G8KSqzqcSOiPmvbRHWDNq97jR2Iuc8G9/5MgCNpkLXUIkKZu5rDIqvEHkZxQDQZNzU2L1DW6D7NaMzq0eD0xoJ4vWmKsUTvApIiC0NxUAA0Bys=,iv:DCLrA2NeJxmp7K0jCrMCW6sAZ1GQjEqlaViz3ICFtI8=,tag:iDxTSAQ2p9YkDDlz9dtY/A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
