apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:A1MECEsGfflrBnTdPlljBPivv16VKDOwbXLE1Uas6KnI0unbxzNcww==,iv:+pd7tKSbnutUsOdX5oGUIfKPPUUeMwejn5BJbp555fc=,tag:cHefqCriYzCkVmzN3QKcsQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S2hHK0FmbTlGSDFtQXpo
            bmNnZXRHRDJsSkc2aHJ4M1VFdHgzd3RLYWtzCmpwVDZQTzVqcyt3c3dQcjZBVEJD
            a3AwcFRqZnNjL21aZ2tHNm9NVlFxbk0KLS0tIG9hR29EUlpBa2tvM05mYnQxM21j
            T3F4djFZbzdMNkZ4K0tDUGpYZStnMncKRYi8eze1vxPSmUdXlkPqJDKkZl2Hhkqn
            lCC94FBg7f5kQuaRHj/XpuM6YVAjJmCSIi7rBtpW5Jp81q5b49avlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T16:22:10Z"
    mac: ENC[AES256_GCM,data:8X0b8SebCOD12S8vZ4kq9bPUJ2yyDbgXA92d52fCxzDIHybN4pGSssoGECUGd90WqLFIl8CPbcfayPHjCP8k2oVp5mZdCmigpyTUlLkSouWUvi6ZyHx7F6i/VgNZ5ZagTH6xbCck94IAuZBLkPTYX1ymYiNJrD/41nlkuf2Bkhs=,iv:TF9uxOzrJsRGDQIiCjJUqr1CtTuclGtz/AfEfDUBaLc=,tag:2Jl6TbnI4R4GDZ/JMGDsNA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
