apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U8rOMnAake6oA+J3BbBi4G2nfR+lx45HRhyAkwkw98dm3mdMeYRbuA==,iv:1PwLKmw/7g21KsyrePeuWtCmuUZ7RoXOwUGfbMbPwTI=,tag:1hHv5e4ZHQjHuQSZBAP3vQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YkNZT0dRRWZNNEtCWU5z
            NUR2ZUJOa3RacVEybmNSY2pkVW1jZGpjSmdBCk5IYkFtQkJuRUdaYTVIK0ViMnpB
            ZXFTbHJ6YkgyZkFBNFRldHRKSS9IZ3cKLS0tIEY2K2puNmZxTGprdUJlUVlDRmg0
            MXE4M2p2OE5SUXNyYzJmUEswZ2dRN3MKjpUEXxMo3mvXCYhUFoyYCiann8BpxaWG
            Qn29qoZ4C/k6Ku8L+5/pHslcW2M/NpW47U0t5DIDmu0zqeJUPYbAnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:36:10Z"
    mac: ENC[AES256_GCM,data:OO1OT+fBJVpeRUw8iGVkqduY2IkbBZEQjL/7DaSoOvGbCV0ZRal4MkVV7tszd4wayF1z4Sgy47p1ao4uPzF8N83CZDbZcSZjT2PbiqULP23I6fdQCmtKc+U/NVlCrUuBb4U71Ufr78eepGn0+jW2+5B3RljZt12u9St/PdC1hcc=,iv:sf+tTLGMAZAPzxzzsui/548Rnu82Q/wZHcyJ/bT8Eww=,tag:dP8NzCkNOrTW0wmJHvXNMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
