apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WvwEvBY65rajx3PrHcSq1SjtuKjS4iwOX/xgPMVxzFCKoQBGGljT6A==,iv:t9wJYRpCztuZGsDH90a0BIxengDR2mBRQZOcaeRxlu0=,tag:vTnBLWtAKAVUtkZktMD9Pw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSzBXdnZtcGhQNlpqbjRZ
            YVdSTW1SeGhld0haeTZKYzVZTEhDcVpyQXdrCmVBOFVzdERtTjJXUG5SNXEwQVc1
            dHNBeFJlenFJWEhNck5YcXRyM1IxSncKLS0tIHU4aXh3eVF2aXY2NmU3dnpXazlJ
            WDVuQUtlOGw3dERyYWhZVnNzTk1Jb0UK95KtWBaFanSlgSJhfSCJuy6XddFjRo0F
            bYoRC1PRABeLXFg+LzHbtZ5HLpHKWTcRXWpA4HNV3p1/amsIXEG74g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T16:15:59Z"
    mac: ENC[AES256_GCM,data:V3PP7Zl3GFgTfOofuLt7b3fWlt7sEKX9DMayRbVBWa2B4DI8er9KOwlIFaCdV3s+bNb9qH2el9llJkfnsrnz18bTOLZBWoQKW104YR8GC12LtrMTPnHGzIGJNPLJCgqDxdggzL/2wFvJyRNbp4Iy3Aopqg93BbbwNUSj7vsPUz4=,iv:476/b3TWzZdUbpps3DzWuKCZ346B+jJHn6I/A4caX0Q=,tag:jQ1rcWsPJUKgjLMq86BO+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
