apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5v0T5ReOHEN0y77GVodDLJYxkb2v64JLECdD/TkaVofo5tDcsy2GdQ==,iv:LqsAXMoyWzUCfYJrNmfA0WdR4yXrI0vSP37vMAncgUw=,tag:X91NdZrnqCSTWOXnqC6aRA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTA1YTRRaEU4NW5JeWFq
            emVKMEFlVW5tQTNqSHIvRUpGckdURHExM1NjCkk4MVcweENHTHVPT1lZRFR2SlUz
            eElGS3ZYSGhXcW9jaU0wMkZtWnloRGcKLS0tIFV4YjNsTUdzV2FHNllySDFYRXhV
            Nk1GMktsUWxoaUJTcWxSbWpHUVFiU1UKVimXXz1FWMZNbMeiOIAOK/CyI1pAB9gN
            BRAfZ8KtTtEdlgXkE59Pe66FVuzOk089x5vvrSH5OECCZUJaM2t1YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T23:39:34Z"
    mac: ENC[AES256_GCM,data:vbcn8xnGoc/5HMB58R0f7JcbtVV3NSMvhjgjGltq64IK+XFXmEC++FkZqmI3n7m72isuj4n5rxB/55ojWhgpJ23e6GpXN04Mx4o5dBBlB7CoJnh9492iOrDKqMuh/Yi+r6KF24sXTtMuLYItPw5avxPOJMvj6MpKllBkREygY1s=,iv:PmlPqhgUEnoXY4UyLU/MVKbXUbXqDqcsnFJRobC4Fg8=,tag:yNJeo8Ukte7SEJYsTaEDbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
