apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fwove4TGSZcj7szIAZCOECVOS1o6N197y7FKXhQF4xMph01Uwr7/LA==,iv:PnYmFXL5s7pWla4IE46ZO8sA1+GeRpnpK1T2PHj0IqQ=,tag:4kkf81uTcMtAoc/AuthG7Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMGhIU3FMUzZKVXhhQS9x
            czE1OTlKNzdwNUtnTUJBQ0hKYlZPUmpob2prCmtkT25USjhZTURKU3RSalJWRThS
            WWhLakZaalVnN29iT0dWWjg3TDJxM1UKLS0tIGZCQ21Bb0pPWXhYQTFUakEySlo4
            TXhkL0VzeGxZRG56a3drMUY4UGt1SkkKYebH9hxH1qRv2ZoLBi5WmvbUMRdO3J8N
            UsTZVk3bhNE+PYUkiF8b8EAaao33vCNwv6dYYhUewLUyyrTUOHeO4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T16:36:36Z"
    mac: ENC[AES256_GCM,data:PnT/4xhh1pKz6cQqmQ9CBxSReqVfHEp9shzbp0nqiNynkGa/t1mpSh719Cy73dKWLt8a9rTGUMc52jcpwHhMRmZoGmytc27FCdjkTeOWDUCN0Lgjxsn6iXsWtDLkOvreI33uhwJXzHR9oagTO1jDwy59Bm2Yg2ZplcvLz4Yqi9I=,iv:DFN4yisJNt2BKyM8/Lr69q9cUIw3jsQ7wshq/GyX0U0=,tag:m8ZHA7dlSanbHGmDkO0yhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
