apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0cm5mA+8QMwu+4S2F0y/SvKDc6Zzvz2jegi6QJypRjdmXpx0lyfmYw==,iv:3fnh7R4t4a8cRnACe+3s/KqrsPU0p0wXFCPmxmc66ZY=,tag:d94dgeU8HamvUK3QF/g0dA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeUtiS3pmVEtFUnEvV0M2
            emxWaE5OaHlZZzNPbWF1OU92TVVRc3VtQ0FvCmV3VXRuNDU2cHA4TWZGdHJPWXpD
            NlRBZ2xXYXZjNjIwNlEvbXJ4QktnTDAKLS0tIFdkcEJUTTdkTkRCK3ZLQVd1Vmo2
            QUxkRWVFc1ROaURERWVHSllwWkdSOTQKslgtf2mhllkW901BsxqPIBRf3ad1yMJN
            g0SOhLMgUGkVSzt8wbcD32eaKaWde+LCjYK3zi+OTuwacBt9pelqkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T21:57:47Z"
    mac: ENC[AES256_GCM,data:ULc+8HiYh96E7HSqpy1CaKU6ll+p9Sdw+hIgpI+ZDisy9ZxJ50WflOKdY/zz9oKkqvX17LkCHPfFsn8uSO2H84JUDRi5iTpg1I2UTpMFvdjXLbr+oB6G/uhvhRC14N00pBW9IheQ6F/J7rw2mHqHsrQeDPFEv1rcALXBYbmc8Pw=,iv:oCEh2X9c5dVS3OXdwRGKeYUHU8Q2CkmFdmZKL4jpowY=,tag:wtTDsPnk5x53S8yOui609A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
