apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WaIjDI3U4aGNdbikO+SUpfjiU556LHoK74JXh3Wh/Vtz/aQVVYmQzw==,iv:dMIEQPvvCDrSUz4RlHFBtSKkfXNT6OY8yZCmg0iu8Po=,tag:WaeyuWiU1pV9Ig2Wf5T10A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldXoyOXBGWGkyay9ZK3Na
            RHFIeVQ5aGhrOFovV2FjdGY3ZHkwNTU5WUFBCmtSa2RDTHVXNnpFM1ZPa2xYNVFw
            Tm55ZEFZM0JPdjZZNjZWNUpjZTg5aHcKLS0tIHk5RXZodUtlUzVORkhMSUZIVGMr
            cDd0aDU5cTF2N0hTNGFvMVJ0akNLNVkKMfvtP2bp27rmEIWPOuHh8IQ/deSudwkp
            R5+YRPj4RaSi6JkVPZKgY4d1dwmdk+lAYSB2QAQpBQwuE6RFNQbryQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:19:54Z"
    mac: ENC[AES256_GCM,data:SVCZv5tkdlM/xvaQ3wKE8yZcYkjhyCJ96UIFNXP3jEhWTr2xzlKhi3NS7d3iFlRv/GApZrvY0lfqUgno1IR7qP07Mz+4NFxykT9kbxX25GRP8zLvClXKHHid0AdWXSDVObG75xH+16hM/Ca+jyXZ62YCHmAB5tZna11oPmwmOUs=,iv:GRnuvUIit6dj4kHiDTHNTs1+zP2nG1z8e0MIQteY2iM=,tag:seOwyc6705pFISKY1Qe2ZA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
