apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UPc2+axphJOCxIHarx9kpxhSsxQLIxQJ0sBeVw2JYndmGTkmD7wXTQ==,iv:u6v8wqS1PXUpj0OeYmaQrxnDM7iQC7phAavHovbWrTk=,tag:c3WocaQcTbHc66ejm2aVkg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jca0kv92mk3n60mwnrf2uwlpsgyt48uz66tudq6g7ud5uuar84tsq8s49a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUejVjeTYvK0FSaFNLK25Q
            SWMvSEcrZysrbVlFMkNUK0hxeG1tQlJLeDBJClQwYzMwU1hsUTZCYlZvUTd4S0dN
            VTlOK0krclJyZW40QWRmeGNFRm5mR0kKLS0tIFNnMXNZc0NEN0FyVlVVdUU0MDkr
            b05aSUNoZmZURWVhUW5NSUZHR3NGYXcK155K5NjnKI7vD1yZpalzT3Gtq5OWanu3
            3wwuTUcTe4su4+z22t8AWqhlsgfc/iM+WQkep1TYxQ4TK9TDZPxqbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T23:48:14Z"
    mac: ENC[AES256_GCM,data:gF6638anRWBxmOkfD4qer0IRbS1IfjRDSih/eYS0QcOcr8eSXi/n6oewDZ0uENJboJ7CpLsyua1nqmIuuSnxXHFz6crW75icuULyJSQhXyix/1LtOlMQyxP5Oi3td0DuGa78MQMvv3KcoGRSjWczOQqBH403jiMBh5NXE0sYagA=,iv:NJtNU4Ov8ooZgbwgP88YPU09RH8cesH8YTHppXpKU6k=,tag:b4s+AK/wuJ9FpCBT4c4vVg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
