apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:akbXkIk2yzV9QjHIAnV3W6y2RQ5Yq2ekj05+Mc5KeuOp/6dWezS1NA==,iv:zzXD1h0IkCKgkGdxbh6g9u7hHlEoiNDQR3cnTZXou2A=,tag:cc4htyemqgnrLEPfgCpgHQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ21uQ2NXcTIrRE1lVGtv
            RjFHMWwycFlSRTN3QnpvMHEzNm1adTdacUdrCm5ZKzFJM0FSTElxM1dwNE9zbGlF
            aWxVOVhuZXM2WS9od1BFU1FVaXZvWUkKLS0tIEEvZWYxME5xNk5rekVtL0JiL2c3
            QVZZeThHMUpxaVZIOUNOQ1dWVDhwSkEKRw7Js3+WbKzT2b76hdpO+o/ZMcigbZbF
            ElX5djOHgra2RRVQb711/JAsWr/av+kct0Ncxht/FIUFMhg38WR4ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T00:07:01Z"
    mac: ENC[AES256_GCM,data:wZLXpIad7QB7ZnCFeqbVmvNSTEPEQ2DFq2dWAzlKSfqqXh7Z5aLvSyGwAFJEHubNtAm/b/g2wigcJSXVAS54TCxwdQL4xsRmRvP5jfz6Vjl5kTwBjc+VzStYDnkFBzrLTRzAJYD0kTz0gHtQulyuWcSzpOCie9EXIR9cDnWPk5E=,iv:NQNcvsWjukaTNfA8EV1fFfToufuxUtpa1cc1KeAjUPY=,tag:Xb3UQdPCe/YWSFS4IHY/tw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
