apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:z5KqxPAyp76I7if8FuVW0Y5zvjC6Cd6rdksZfSxTjDrJnNegeobtaQ==,iv:s7LTkGpY35Fz345ITBjoi36lNEgzyVWfo8xCQRXi0RA=,tag:9YKMA/dxw4k72DZSA8w9iQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVlJ0RGp2RU5sOTVjdTRt
            YzlqZ096VFRSZmM1UzJsZXpRNUdVTURRNzNRCmFHUUhHTG42RHdtTFZjbjZQcm95
            cWRDNW1pQmRjaFQ5YkVidmNkQmdZc1kKLS0tIGltdWhnOFRianF3Sm0ybWFobkd4
            bzArOTZJSDF4WW40TXlwWnUvVFRwOXMKtRoky62/3Ug3llSFdC+1qZp+59qs0xYc
            vyUtyTsh26hZ99QpByqr6FYOlkPqmyCPqONO1gwJL/uGKKh5GD52Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:33:23Z"
    mac: ENC[AES256_GCM,data:FGRlZjYkqIniJjZzUk9K0wd7ueoi7RIB+rqTUmPjyCPltdRwwyfxIzmdoJxEmttblG7cDlFTZe5LE8FkOgPpAfCEvesB9sZ34LbBlj/pFzrCjdil4C6gZud99qYcxvxwd7EolF/OkMZI0LxZU8E+2g6BfVuk/jZNKfb59WLco9s=,iv:cfHErfcyCy5cn0W4dmlptm+NK3pMeiqPXiouSD/ase0=,tag:DHr2DJTt4Bfy5iSVJ4SQCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
