apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:upuAD+sGq4PBRunViLWvaodxN4mntHpEgyAm4L7mr11n/nXs1PvEUQ==,iv:IxQpiWqPZwK/wjVH+Sngw8FolvT3f7xaqSk69m3anpE=,tag:Ar0W1hzgM/sQhc2VxGK8ng==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0N2QWhTbzNYTk01MWh6
            eS84R1gyRjUvdDlad045eFVsWk1uektUZDBvCko2ZTd4d0VVY2NJQmhFeEcxdGpP
            aVBVSzdXUVo3eE4wU3lIOGk0NjA4YXcKLS0tIFY5c29hZTVVRXJTQTd1WFJmMWM2
            RU1ZL1htME5UOFp3a2k3S2VFekEyMmMK34lrSB+O3oUJbYAyRElZwntezqZJSQKp
            y/+UZtOhc0t5BpEdWhksnlzIv4ICAirSAYdYTf1jL9wf6HU0M9Zk0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:17:48Z"
    mac: ENC[AES256_GCM,data:TRfO+9u+MncNY2yzT5uEA27KwUwgJ2IecoedFgR2fc8/akjVKj+C/EjAnaV2Tge4l6JptKKOT31gm/t9+XaORD4S9dSz5jGKequq2gBMSXNJRQzQCx+NjicGk/RjK9qlXB2T/cpvMQONc51ft90XQk/jbRT0F6tcARPzjLIdM2o=,iv:dMgzjzDCSxxfo535Bvzts08hUEhMLX7EOS/9fAr33eQ=,tag:f/P0KxbXqICsLy61PVQOwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
