apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lu1BoV6u70C8bAcqIxUAdZsaudYgR9C8+q+3If9IXZmcghLgAzuxTA==,iv:LzpDz4wUoCpf+mY0LcvhmayvMNOBChWCvuoWm4/i3pc=,tag:TyNA6+iZ+LkH7HKm7DJ4nA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SXpWb3dqWGJ2eW85QS8w
            M09zOXF5bUo2K3R4Wm1mZjVJckd0eWFqS25VCjdrVkdnMEw5K3JyRGZFOUVqNmp3
            eHZYdmhHOFZyTHByZWNuaVl5SVpIQlUKLS0tIEJGWDcrZkd5SkhZa283MEdWcjla
            WndiS3UzVElqWlViNG5mdTh1VlNoRjAKQ/Qie3sG3Bx7FC+n0Sc+Lcb9fxct6Bpg
            rt9ZVWnPGAUuXqKdNkVRzW9q0rGY1VHqTSFbU9msFKuazMZIvzUyng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T00:02:24Z"
    mac: ENC[AES256_GCM,data:tYT0X0RWfN1qqoeaeoTiTEudsFBgcMD79Pn647iQ80HOXjRdBulCPQxeYKTUbMnMNv0PwuDpi83m6zU+lJsoivNGkgWgobyxN2aTxVmp7Mw5sXwmN+YzOm4kkaHHPC8OfTw/SSJT1lQu4ayMVKLOU/7ribz7JDAmUMius+a/nuM=,iv:eAQSsHTZaVEewziS4OK7WUtmVyvGfWk+M3gZS53rv7M=,tag:NkCgXiKGBQ1nPoq5S5sS0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
