apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rv6USgVvQsNk3ai+Qm6aDkD7LCAqj04yNEmsqsue+gvVEF7M1JzBew==,iv:FRE0CedjaZn4qG9MJNsLg3a/bujqN91pEVLO3Vtrpaw=,tag:tQOl9/PnW41tPDRLwy9JNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aHRuTjFUdnVveDMrL3Bs
            OElzRG0rdDBWM1VRRS9RdklpZTI5ZzlvUFhBClhRMUh4Tys2RTBROTZ0T2FKVis1
            ajBmaDdFdnN4NlJFUEFZVmJNSzYyeDAKLS0tIDgrY2tZV3JYUUlZZkZzcDliUlRo
            NGt0clFMNk1sTTVPQTE2NXVQeS9QMWsK0ERdQTZmLaTTQOCwCSCsmZbh+0JR0i6f
            D+vyR4uG2LFnlr6rBE1Erb8B+/jkbBvIBkN+8nCXBs9FEamRJml8Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T22:01:30Z"
    mac: ENC[AES256_GCM,data:VUkY1M83rLT0hf7K9hsQgUmiPRJcRGX6CuFi+O4gowG499UY/wntUrRCSXAmw4ZeezVSxLV92ORxIaWO+Am1G7wHlGFbMQcY0nMVGHEWnOEf1HuT9xGNQapzUyzo4tEC/r8p5wbdPwBPeG4DLv2ObgwCWC8F3cNCxBdnxu/l1os=,iv:e0h7rCMiFc8w77V4vraKTaw22Hy492oxVBevKwVVJ+E=,tag:OQM7t7jFlvsHCLHuvlArYg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
