apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tdMp6h45pFueTLn/Q/V+vLVu2cR7mDfk+YczzZQ0c1CBJqB2Gvtdfw==,iv:wQU/PndUkk1ITPnsxOu9jlr6XSO2PJvUs+dQqy+nDUI=,tag:mf5g9NqgBdzTkWwysRjLSw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ0xsR3N2VmpROGxtWEhh
            RjBzV1lnNUQzN01ncllJbXY5dVZVNXZpR1Y0CnRabWVTTFRwVjlwaU9wZzRvVUlx
            eEFqM3VSU1REYnNrOURDclIxbTNreGsKLS0tIHVvWnc4YkRJYUxLMTVrYXJzYkxz
            VExoVzlhWGxCZ2ZLTUE0ancyQ2NmeG8KUJXAj+KCH8m1LU6DR329Hgl8A7LUYbLO
            kuXXarlwcBrOatXMFaf7Ar9PF2iyxWz3CfqYfdme6CCwYnc2HPwi7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:56:34Z"
    mac: ENC[AES256_GCM,data:1p8AP2VAfoMGg88Nm8w2s8ffsRX5TpLBRIQBRWvC1IdeJFAOe3ryeBTk/GdThXJjqSfROlxFD8sSRRlPULomLCZiSG/nJE0Y8bVoXiZdu5B6NMozxBCAgqUG6EgoG0Ze4f/SFpyFZ9erNJuw64vXn2OP9kZtZc1tfot2zoR1nzk=,iv:QQP7jwk+lvjp6x5VAPILIM0fPCbna5sGRIieE8QiEcw=,tag:jW/gvkgyafYMBrm7pJdq3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
