apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l0I6DFqk8lAc75ZbD7qlrMzaMGsh0GJZ3A+G19D1C61TzFjHmRxVCA==,iv:mGRTeNSnvdoshU4cTmw5u8UD0airianvT4WHD7Cy6zc=,tag:g6yjxvdWfIKWSJH+YRsjEg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eXhBaWYvSk43Z2ZmZmY4
            RFdrWlp0YnhsUk5jVTJYeXhHYm9IUVF0TEQwCnFyNWg2ZFp4cCtJT3YyNXJrZnR1
            OGhXM2N6SFNIdE5qYitrdUhoT09FdVkKLS0tIGUvNE9IUE9tZU5WbUdkdFVnMlNx
            UTVjUmROd0R6N1ZST3owbHBHT1VlV1kKQmWo73OLK3CZvN4EatHDjT5M8t6kIRM4
            vF0tyUWxfcC9L7Qa+3acrVSqplKT7K3CS6vKgtBLEXMkCGwQ8O1dSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T01:40:16Z"
    mac: ENC[AES256_GCM,data:8q3l3kl4F/iq3M9uh2Q8UDGaJxAhTPgjqrxMUH676lgYyqplbZIUGjO4uASmXRLdRBLIXN8n+NBeSSXFik/VLBJUAR1kLivYGVl9Dn8rgqYy5/0JE0uSygcZBLVvC5LPYFed0HOZNAb4p4qSYnuo/0B1TyXNVANSVXbdATj4W3Q=,iv:b+jDmkOLZpDtFzrlmnCL1fOHFbdaHU6aYRJ4SpR5a6w=,tag:guO0haACOYKBr9pw6eFqTw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
