apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XZo4T+izKJ/P3nhJtNgzo+qYAJ9CyixDKMjCZPN1SnxGUtKxZ43MNg==,iv:3Azm2NcWpl7BOLOlSNxFYT0mMYUCuyQ4PAkTAM7daAc=,tag:xJnFGoTEEVHoA/uMd/2bbQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR2xWR1J5RXpxRnRiV2JH
            c0RQNSsyeFE2RGFXelFYa1phdlRmUnkxazBjCi9DZE9iNm9zSnpYNXFYbm05TE5r
            dnZ6L3V6NkdZdVVFaFdpemRpRllML2cKLS0tIEk3WHlkVEdTZEpNeFNnSXVpcjNE
            aDJhdXFLM2pmcnphdWdVRTZDcUw0NVUKnwkyrgqlM8iVjG4uqe/P/oZ/pkXokUKD
            E5MY/0ftmf8mG49A7x4KeAy6vmR4oJTCF/SPn27s6R1swlPQjQ4Qtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:25:05Z"
    mac: ENC[AES256_GCM,data:T5cBTGvM2kLpOrWqckQ5Nog4V4R0+Qj0+Gk8zBI/HdagAojjvyZahbbXHgxLsNaEOOQjma6j6qfw4njal+euUFdFkilBKrHzdyPicMXAUgLbt6D3BVqXQolCpaJ+abXG41eY7ccVHPAAPNTp6ThFZscVf0sDyHIBw47t+DxSkhE=,iv:Q/CbDWYKpfTHwJomteDz774pFQC91cuLIWCEqS5ZyUg=,tag:BNu6ygzZt2zI2qpqy/CtMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
