apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:duoYS/Pl5HbUw26/k2Oe3y0LRV/vIMHRl+L4SuTRKR3ooe3xbxIvUQ==,iv:o30hT+fAlOTq39GJBfDBzF78N6qEQWdNt85+cBjIB0M=,tag:HoXDazv/ijfREjHcMHgccA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWDJmZ0tVeHpKVFFsZlRD
            K0NncnVEVFg4VEdoaGhDWnU4cUpqb1hlVERvClk4bG9UeFBJTTNGK2hWVkE2eG01
            a09DdkVFTzFQNXMyeVJ1RHlIZTlHTlkKLS0tIEV4dGRCYTNUN2x1cWhoZkwzUTRZ
            QWlFUG85SHVlS3BwR0FwKzEvR0x2ejgKTw8+Y4GiSaJdj+F9/v0c+gQwRPaHz5y4
            T7awHJozKIbA4f84bLXOPMhqgFURy7iA8N4O9O0P9syOWRlUjvap9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T17:26:48Z"
    mac: ENC[AES256_GCM,data:2cEbslgvkFDm+33HxhUySuSQABEai93l1D5rCyBb9tUGdOm9Qrugz7C3cDRbcW7FB+cQfroNQXHFTIJ8KV75iujyaFNE3BsZYWMkDnw+MXAAvHEc35i3XY2htMCoq2Dt7x6OFUhc/gFSdk01xsaaefPMRlht1tvmGsDeCOiqYxo=,iv:XzDybcgudbJF9fNxt+8cHndQ+20bpiZ2a9EjCi2COPU=,tag:lU0eZQ6Q2MtgyR3ZFbEhuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
