apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0rCpj7G0nxke8WZ2Jo5pJaN+KKDLbV0RhGvog/NEP1iBrpPY7HFAAQ==,iv:j5AtXaxhHnrzZxMd6I8D2Zgpi5kD6Q2YgYvCzaJlXFk=,tag:2D74YFboFGzuXacpYGuSVA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQktHdWljOWs5a1VsQnRI
            LzludTlyZ0ppdXJkelBqSDRQdlFHQ0xTRXhJClZZcjU1cmY2NGtuOHN3akRxM0lw
            dUJTbUthNVBSL0FEZmdvQjNDMnhxWkEKLS0tIDFqL2FjdGI0WnJIVjduNkU1MGUr
            T3NVTTNtNWp4Zzk5dEYvRHkxaDN4cU0KhM20cssi2Qb2vlMe1JHJBv5Z4/FPJPkn
            wc7/yrZ4A/qBx28nEAeojMldudi1W/D8pwKP7TvA/LReRe/S+DMZxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T23:37:31Z"
    mac: ENC[AES256_GCM,data:VPwZ+EI5MVbj0FQ1K7y87M8dqS/yYuVNOQRsVwS+8FQXD5DE0MuDr3T6ZpbrRIwJhU4Y0RfMfKD0EEzGl403bG7FFEAWjddE1UFnp064kMY74Dq+Dv0AW9jM22pOxXK0/Doxp2dzdv6N7kX7t+RNdLK4s+H4NM/Z9PL3dQh/GXU=,iv:eWuaQEwxZIjb36FAIEdP0JKE7wc/Ww+QQgLXnZ8omsU=,tag:c5hxwDgTdqeD6SEELsyLMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
