apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cmo2aSc+NSmwHvJJIQ91ooyf0wmQ4folowuhZL0eAtSCo2na4kSXFg==,iv:rCakj/utoxN5QMLnR2+8B45CxO7aOF1qKVqfBl5X8Nc=,tag:7hP42U9MJ1OqcuWW0gRL4Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWUUwWXN2bUNZU1AyNE9t
            RTBZYldJUGVFcVBTL0ZzZUJacnE0OG5kdmpRCjFmYlJ0OWtxNS9kZU1jcFptMEFv
            Umt6UklzNmp0WFhzbHk0ZlFPVUFhaDQKLS0tIExHdCtTb2I1cnlQbk5JVm93bmNr
            dEtleWZCZ29ybFVxSDgxZkMwNG5tRlkKCusSRUGfDpNpppbvOViuw5YTngzZvPaf
            HIQp77zojZzJQVJE1zchYrABfEvrN/5m02KDQmxE3N1Cls64y6PxyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T14:23:27Z"
    mac: ENC[AES256_GCM,data:3xoVrcAZHik9D3etu06g4uxTWVEklROtEdjqkye4+IPCSlVikGDmtadqJ/BlC0/frJDExj3/IzmS0kX9rPBKCcpPcLzKXwXgOfkg603xvLNxCLTLBMd2rTZQO5fn3X3kPerKKGQfDuEtTvOXtQOqHb/ion4bHJXZ4wHhJU3bcBE=,iv:dkWiRXKCKLGvYOjqXuBnMbSA5CiCBEMnaYbo7W8Dfp0=,tag:CsNG4Hc0JPKKztwwt9CrcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
