apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:i7wnB/Bht08SrYZUnR5M4gYQeiFCOE6w06eOlTyh8foms4RFi/yFWw==,iv:Pr5iiTsaCjMWau4PNCwILRWlQTTo4jjWXX0/4E7eres=,tag:ZCJF8np933XVlyLtyB8Evw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RUw4bC9RUGNMYXZiZnB3
            c1luMFFXM3g1Y3RjUTZrcmNpdGl5RTRUNFdJCmJWTXluWEdKeExXT3VmMVJkNytP
            SnVmY1lnZDFpT1JQNzRVMTVidEdmcDgKLS0tIFFhWnJ2NkYvSGFYUDNHRGMxRGl5
            MkJqMVo4RUtLcmtlTkdxRWtSQW96UGsKM62BUQ8xDrM0JXC04gAB2STOrNxibUE0
            gtlyZIkbYXEQ4Z8Hgs4v9BX9cGnbmJoMu6WamdAb2iK2OxYgnh+FZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:18:34Z"
    mac: ENC[AES256_GCM,data:A5VTeXsvrXLxLYwed2hdoFQYj1xP8n4eEjOUy//EZhZlt78PMGXCKPhjJ38OhLike3I+vqaTFoHHAv0ExqQbTb+yrrdsOqOtXPrrWaeuvYMDKnTbTDMH0qoi4W6tGznlur5CNvZYYOye19NxbwFrQnlZKChiaG05DMJ5mVKULhQ=,iv:3GIXMGDycFh7c5FuRAuhZPjUjEFy4FlingPqaM/B36w=,tag:7uS6xrMwssnfEtmDwVxB/Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
