apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:o4Nm1WjJr78xlqDWQdjHwVcxvwA7yd+KCvYWKrJIFq1OdT1wMlxmrg==,iv:Vrqb56QsDQuIUKwt4pMWDhISuxOlHRzFRzVU3udX7hg=,tag:+MZPBMM9QTCIOCgJSUqUTw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckdBeE9iQUxySUg2OWtN
            N25sYU9aYTZRZFFsV09PMlNJS3dWYVJRTncwCnlETnFPOUJzTnI3amtFZU9VcCsr
            Skh1NHhiTWRodVExbDd3cUovTE8vUFEKLS0tIDdRTU9PRm13YlVtK0VMY1R2d20v
            TmZEaFRHaHRFV3RXcEcyMzN2TGVHQ2sKyJBC2j8eCPbUH49qpMhfQ2wPMSaAFYxK
            kTIBpC6B103Jks1sAvn9P3+bykWFDJzRQQKIniWN5IcLEpvjOsoJGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T00:05:56Z"
    mac: ENC[AES256_GCM,data:uZ6uIug5vNqoDzzCaaT8lcFR7VZrv/VQXOnpqx9Q2HFe5wUvT+1rxiNim9x8LsOvw2bo6HclSP+HE6DZgzC6RJ7Ixg7VvM4leZgkmX/w0MC57ip00XL9w2mLCR2OaiOoRAljPsJhc5O2Tu/hweVvI9OoxdsNiHkGjAs3HA0Bmg8=,iv:FsjU0V5m5BeALtsAdYI313LlkrRdtWua/lFewaUFFSM=,tag:aNWMe1Qu+jZAg/JDS69AUQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
