apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:O5M+d1Sxkzwu6Rhcgj6O6CjxfDP3vJ621d50Ffa6j92wbpVp4TC5vQ==,iv:zBuftAYVMT5S4+hAySbIXSl0HBZtEdY2vKgmxe+cD7M=,tag:Kh6xO8sqJNfUjDSmvM4R0g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYlJ6bENYSTZQNEh2NnRx
            QzhLU1ZsaWp3eDZGMFJqeDhkQWRFV2ZrM3pvCmpnUzRnS3UyVzJzRUFpUThCTnEy
            S1hlRHRDeGttT1ZrVjdwaWhyMGtJamcKLS0tIFIvdGJrSURYWVJUM0g0YS96VHJH
            M2k1OWlWSUF3K2p4UDM5TXhRejRkbW8KnadWa67ssIbmqlU8rC1apW12xEbrFjB7
            b1TNcVhex9sTBYL+FiESJMlbhI3CYrma2laQubEeW9VKr3+wDTw4vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T17:14:40Z"
    mac: ENC[AES256_GCM,data:2LSujykASZZy5Y4siBvCmrEpk0dcR2+CcWhoQNcsFBxsVAsVeuLHJhZxBNUYGW8qWjTG1HoFqazVbAse0+Irq6fTBaPHqaw2rAnNHopnxAy7eE9TYhtuuyV+FrRxrlO/TF6DLbKmdCudigXQJDSY8PNs0ApzGDobogZBd77MlS8=,iv:jYnGctWGBbcRQI4L+LzeW9q6sXxkuj03mqcr806KPZk=,tag:Kk143lSc12YsASsIYSb1ZA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
