apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:v2wtZ1in8prlZc/FTVFT1Yxm1l1ZzwsvR6fNn8IxAzl7REsV0KABgA==,iv:tA98+jLbGq69FNhDtwX3WCmq7tbtD5V7/DHXrwf3TLU=,tag:0E7gOyHpZ37DuODQKutfsQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y1Vxa0IwV3EwNDMwR0w2
            SzJmT2dtSlNvMUNJdEk0QStRRlNGQnhQNGhJCnFIZnNDMFdVL042Slg2WkhWRVB4
            RG5tVmcyS1FrMDFQUlZuZFdZMUVoWG8KLS0tIHBGdkQ5a3luSFhqaksxZ1dUQ1Jk
            b1RWMkVYTDRRczh0eE1VeENiVUYxUDQK1xsCZlZB+Fjldsq7L5MvdlLvxEESdgyM
            7b68tXCfBQF8zHosAI2PSK/ok8t4ig7Tv+n9GzZWdayCHhezHaStGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:37:07Z"
    mac: ENC[AES256_GCM,data:gSxT3YvLAfL9ZD5OzkiPAF1ZXprNJxaSS6rSz9EypQVIk7rJsXwwfvvYCvHgGZF7KJ3ZlUS/3bWHTRlJWTMd2MUNzgRjXTY1t+9vqogeR5DbjFvF/uUEWyiY3hGAcAaq9je+R1R6w5oa18K8VN/4LUqF/y9O6YBadBAjGbdp4b0=,iv:RCFa882HfenryU5eFoyXNDw/HrqsyhCznLMyFQ1TGYA=,tag:QEJaNlI0XnT0SuMGyGzJjg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
