apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ICXKV1xoC6VRMZSIsqIIY7doepeATLLc1GirV7BIT6TJiCfw/Z/4bw==,iv:BCKZm7yWgO82JVSGoa6Oi+fW0mTDO5YYqbcykc/BJlA=,tag:VHOHrckErL78jdU/bTLnEA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M1JIMDNLM2ZrRUxpMUl4
            VithN1d3SnhVZElBSStRZlNzNllncThIY213CmpZV0N3MzhlSmx6Ri9jU1dXc3Ja
            QnhRTTJ6MVpOT2xGT0ZiaEw5aHIraHcKLS0tIHB4YWRxbGNSWFhTZWhpOG9iZTVL
            cVh6VmhoR0QvamZMcjJSbFhFWFZiT0kKfLFIECascXa5f88mbJnLXMstj4yIUdtm
            UXaR6KQRR/HmB1NcqJ1Ol+DzdFLuCM2fJrxQfyIwYax4wjN4TO45Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T21:54:19Z"
    mac: ENC[AES256_GCM,data:oTIfsCoU5NE0dhEU89hzQEEUZQTV7RenxtjRApeI1aXpVZwlR+tE/iSUKEQC4EXnqzFeJpllryGtaZRlprgku2lkaxSZudqOS6t8qKuIhHe8dbq9nPd4Qx+DdjjD+8tUtnG5edUrRHCRUd3B5IHCrNJ5UfeD8V1/zAfC7guegtg=,iv:ki7n+uePmZfaAdgXIT8j4y6r/BEG1eE6c859nEG1dpo=,tag:X3xYa8ShlLHrPeCn+sUO8w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
