apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FTSo7bUEyBBFPyLiDeZP2Lge4JhOvDWgegaqfwjO9yCnOxyWfDKNCQ==,iv:VchtbpymRKIt/7N+tXPoKidc97gzVDMqfF3g/uyRopk=,tag:hv0hUUoQFTRHXjXvmnCkJg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd3VYYXoxWG1wZzZkdG1v
            c01SMFlER2d5dEhEMDhtTy9NTTJqR013SXdJCkEyVnZMN0lWT3dNWHlieDJzUXc3
            cHlPOElJSXFsRS9Dbkx0Zjg3S1U2L1kKLS0tIFc1ZnZLWVhmZk5aVGpYMzNLcldl
            L3RFakdTR0QzbDdzb2hXMjE2WFFudjQK1lL44YfIAGyNlTTRTvRWzkgBcusefW8R
            p3C5okiZlnqFo7DeVqYZXOyo5gVrnoXN2IbM+a3h4HiqQdk8hBglBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T23:29:36Z"
    mac: ENC[AES256_GCM,data:3AUXO4tAA3ajEYbToaW/GfvWWLGu/FLMsqXo581MfU0UUrcG5iMQzeJ9u5FvpPXJkuqLe/X6ccsI2nfki+ArpLurQJjWvZqQutM7XMIqIqnMFJLPj3KtYvITALNkc/+6TghMzy5CNDuk0S2qNTaSvPBfCfa6dCyARYcK9axGcAE=,iv:hZ82E5U2xYWzyymywFsUnzGRLSYttv+GYj6JSVRkVHY=,tag:GpqCujzqz5QkwpL2k0ZLiQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
