apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8gfRiRa3y5Mnc7ywHlpPiqI9/0tHh444ZBX3csZBuTjSyMlRl2wVyw==,iv:UoNrs3wJsK989NU+aC9yFq+17WoSkmiBr8bD26ulkgY=,tag:eOYJzZEyv6L3dNpEzddBOA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VlBEaHArbEdRZFlqVVYz
            ZjdiUndROFhvYkdBK1QvOGhSRG4yamw0dGlnCnFSaDRwckRwVDhjN0wwbXF6MzVK
            UWxKUEcrRDM2VnR6WURjUE5SRnZXRm8KLS0tIDN6NkpiMjJEam1KTzhYb3dQVjd4
            U0hGbFBIckpNK3RCS2VaS2VyeU9zU2MKJWE3cUdJBSJUBkhk2WVObGvbsywOx/70
            0ScdTrZq0r9JoZ2NHysX8uRmW7DWJpgFMsqC6nWHkJn5Sp+dzju8FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T14:57:21Z"
    mac: ENC[AES256_GCM,data:xDpf3JHkydf5qasQ54lgGSF8XCcaaG0QL5UbwGLe3xrDwFUMxZ2QCJsREm2xA1pvvyJYECMblBUnncaSEf2udES1n1TspuypSFE6SgF39+Q51QoFaRRa5x01BAHmZMjhphCfKMZvcw1QOmz3uf4HmLFAA8jojLUv3CpFSxsSexs=,iv:1g5We1qYbvQAI/J2SJZeWK075L17VuJKQ3MujmBY1Y0=,tag:bXapKYFmOz6RpkBnQX7ZVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
