apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - cloudflared/ks.yaml
  - ext-cow/ks.yaml
  - jellyfin/ks.yaml
  - xteve/ks.yaml
  - hass/ks.yaml
  - immich/ks.yaml
  - nextcloud/ks.yaml
  - vaultwarden/ks.yaml
  - stun-turn/ks.yaml
  - speedtest-tracker/ks.yaml
