---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: web-server
  namespace: web-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    image:
      repository: ghcr.io/traefik/whoami
      pullPolicy: IfNotPresent
      tag: v1.10.3@sha256:43a68d10b9dfcfc3ffbfe4dd42100dc9aeaf29b3a5636c856337a5940f1b4f1c
    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-webserver"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${WEB_IP}
        ports:
          main:
            protocol: http
            port: 80

    persistence:
        html:
          enabled: true
          readOnly: false
          mountPath: /data        
          volsync:
          - name: html
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 23 * * *

    # workload:
    #   main:
    #     podSpec:
    #       containers:
    #         main:
    #           env:
    #             SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
    #             SERVER_ROOT: "/"                     