---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: web-server
  namespace: web-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-webserver"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${WEB_IP}
        ports:
          main:
            protocol: http
            port: 8083  

    persistence:
      data:
        enabled: true
        readOnly: false
        mountPath: /var/www/html
        volsync:
            - credentials: s3
              dest:
                enabled: true
              name: data
              src:
                enabled: true
              type: restic

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                SERVER_ROOT: "/"                     