apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tLFCZ+ofUh3HJ85IHkoZElc1pq2IF9/VsmSkv0ZvPKBxXVhqdyR189Q6phMe0/6qVMxNX7X4foWuGOjLdoJ9iT3sNPQgeiBcOphbjtcsF8pqR9ZHNWJKGZpunXX5U9QZkeblOWAR5FsPcI40HcZJ4TXd5AH5eNCchFiZPvV5c1XhAxmTkpPbQuGHJjEAbHR6Ppu0JvZgYnq8hi2MWh/J1MYt9Np77dZSWRi1dHir+BiOl+ZS4UY6Ncui4IMdAC4b3O6u7d+iGK46DNit8pTvGhqCtJrQoJU/45iUZoCL89iWzwzErhC1/kYUmSm3QGxCfKM5zZw8yfEEp9hAjKQHjR/aKuJC7PtvUodslTy6VxSHwPK8tFhZb4qShFonVaWr,iv:JF8Lj1Q0/c/GUcUnVQYoVD5zK/QoYL4TlkHThG6Q2yo=,tag:Otm3vPKkIpBGUPteqL6PGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:A95opPDFqozNuOHVkax82eqjuwNXLLugVRJ1If6xcXUckxmkBSJHjyjH04d7LKMIFSdsZYhsFwlPUhyZL6bjNv5AeV7Iei/VBglDGNedpk0QJ9WIeBEQBmzWLs/mytIUPyLIzWTuJLivGBFqN0kPa2XzoMGR9PEjRvzN9u7zYd6zR9QS7UyK28ArjJP4TzzGNOdVrgNGlu8TxaCtMYfYggQJzbIUq8VwTz3uAkGGhrXyoytbGbUcH8O7gE1fYhti7LIW7sf74jeGZzv04Q==,iv:TITlaWyKBlfgFxRUpE3SIrtpEdnOoonMfPsdj9pXntE=,tag:0IGaraaff8HhBLkimcSd1g==,type:str]
    known_hosts: ENC[AES256_GCM,data:ewY5HFwaJd644EHRUWUjk+N+0QR16IjJMqfbW+lW8DT5W/5xV02Pme3IvZlYMuve8YVS8tKOLosCwhX7s4peCtEL9RclEOliegNCkVCFk4V1eyIXR5RC5Gk+qwRNYujk/iUhf/9BuZ6K97cJpv1VBiqAF72S77r4LAvjzbaVMorThxRux6ow3Z3R3rxvYsKuiC08yBrN9Gp3ZKYwx99ijXWQzaQa9x/1sRhW,iv:znEGRRYBfsCf/WnidhAhTYDRu90+zAnQoGKRGWa0Ias=,tag:CAVW1N/5nNx+HEJGzHzv9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eGdjN0hrQmFEbkwwY2Vl
            TnR3aFZVaC9UOURoc1Myc0YwR2JBQ3lFaVU0CnV1cG92NmU3ZHA4b2RKdkZTb3Js
            SjMrZ2RwTUkvMVBZbmFvTmt3U2Z5OE0KLS0tIFN1em1CbzdnVXg4amNicStERldn
            ZUJCMXZ2Z09tbFFSeHp1VzhvN253bjgKWZdGrRifWz6ugDiDCsHOkPSF88mJk5Fg
            SaWaDC0aPDvWiCPbu0l+nOwBgiHQ6hVcu2BrdJkRl/vXHkomcAf7OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:18:34Z"
    mac: ENC[AES256_GCM,data:UwcMhZASt0d+pZ41gqKJR9bT1loXas0/ZWAABp2a5U6pr2pkruiiaDgvMpRJQt0M/z0mv89HeZP92dRSMllA1FtNhFWA13XpBSf61JgAG1QsSHAzX1vtunkn+GuE9PoByV7uoMovLgz0w+/5e9LEg63MI7RwUTZysOs5z5irPdk=,iv:kmwyl9/W3rwhj/uxJaTAoE4bXXsL2aNaazcJFA/hrdA=,tag:lK4NrEsVkLOSmqEYvFf+SQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
