apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rNEaFn/RU4+QNcUfSmYdvKFO+JiIzDHOY104QyAKT66RT6OLOAp5twWcbRo+ylYIvadtpE2LSBY4BojrlnZLdw+W3uQk6Ec1rmhamydr7tJBqPrJvSkqew25ERugw2ik05nca23isDLEOfqHe2ETxMAXrcsWMYR4mMwN1dB7/YEQECue9FdenLxz/uXmf/DQnqX9LpLpmtexXi7SuLhJgG2qtgiRW6PTcPNruNXkXkkbmD50WOLn4VsFmAzncwmBgk4ZMZtKvgMckkEvlcmFTr/fYTjN3oWQplQi3Nresjp2UBv1aoNdU2tRbXyHfgkPzncw5EGsX29wKr8rCc750Ehs+WB9KNjXurfL1hoTFXv3Wf04W7Vf60KB01WzokW1,iv:bfCkfS/4FoB+NabCQvfCOAjYEgdzJQ2upu+tPuSuAD0=,tag:5p/uhuJ28Lv4uEWPZAvaWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:G/ahKUgkFlRY04Fh1XSN45lubCmJOK2VZbw7793kly/2aQr4kyWmooeh0OhlYFmyn6KnnautxFw4gkGddIfCXbwdh36lps0v6rdnMDANknVgTAYGbxGQXvN72iQi23iokN6+0wTOoPLIknQskw9WCkNol2RGnWx6cZovNY/iY8LZQ4SmJOORproEXeVRnw9sHGXNy5EdImx0U/b9NL4UEL3AVNc97UcEGsiglpGibgAu4CbU6Qhh8eP2HSWvOaqVOQThsdgD6i6NIhhmvQ==,iv:mqrZiAM3tjB/RVdDy7w6QkMj4OErz0YX+PjSegf7O6Q=,tag:v4Xiy3HJHLXbflNbSGw6Cg==,type:str]
    known_hosts: ENC[AES256_GCM,data:IykqkzAf+BaXJPfkqGckn3YrWXJU+1/skLXV+3GtiJe1aobblKglRGyhV/5z96sbY01bHhLZe/ILLgDuxYQs9GeUKGM3b+NT2L0zLa+IxrvD6QYZXafidTPLj3M1lULRSnZBRR79LtJA25wfTLXOqmNwaajmp4r2JoMII2h7gj11dwWAyh+3dNLScjdw2OPxC/UjwfrS/QzSBcOJhLzb8pXxo+CIs65dqLdA,iv:I1uUlH8/rmctabZVMjQKoSuuTrpQ8L86l35ovdoL+Jg=,tag:gIQoWJDQlphRa1Q3EGWk5g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreS9qQTF4b0J6OUV1WWdP
            N1ltUlJHMnZkWFFPS1VzRlBGQ2kyM256NFNVCjNUU1UrdTdWakhoYTZEeW9GRVhI
            a2lCbnF5L0FvY2FCbHU4eG1RUXFlYk0KLS0tIGlXY2VjWjhaM1Q4YjFvTW9aK2tV
            ZnJqdS9iVFQ0MXFJeEs4QXphWVV4TXcKNfXdGCYtqn9CMQw+vyju9yqYh+J0IroF
            NT3w2yvWVpblAXR496npPrTD0FojkNYy7fMDRUKEF8AP2nHUqL1CXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:34:42Z"
    mac: ENC[AES256_GCM,data:GSQpxvGW5jT76+QaK62X4+iq+iGrbpdJK1TZwA704g8SuS6z/2ZoNx9UgpPg6sdlGHuyiMCOioyfRgnqMMl6ZzsA3plFj30obLJ06zEYQzHnqsgLftNK/Y6hTDYpbZeAq6RLutBDpETl5GsMconY93m1E3q7MGD/ojcumomIH04=,iv:E6P/c7IMvhItY3tKhifFcCm9ekFlu1UcV8950AVtKLc=,tag:E6YA1Q92Cuc3ShrjRTcrYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
