apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+xS+oCc19/1mvbLccY9nTCpyVNTVwa/eCpfwd8h0CNv4JuTKPt2z48AuxG61dEKyPxa93m7nnawz7GkJC0hjQSm/Y9K3cWSYy2XNf9hkFoXdlJNdxCfgSv0fU7e61ZknIJyxRGK0ws1Are6STO9AQIQwrHZKCbDyl0j65vYvhkZziRl0pUdaZecbWWQv7mY7q/gbKqSRReGUn8NorauZDdBmzsymvWn5CTO6LJcA/c/p6TXJ/nsaqTfzDqrTTq3odnJG0yGJzYKH6AdOLuZ8Tzws7BO5hpoPQkNQ97u9XrQzs9NtCEMYtTx8xDQqzAmPIpvIre7XxtFqh3tkU1+6c7HKFGIqYPT+ITTd2Cak8QAiWvIEk87PzPq6W9z3QpNI,iv:pFp4UoKoWGPPWZX8Yy03lBMpzZQLBF4CjvurH2DJ97c=,tag:Nvm2gMJEEaMOYZhpPILVNQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oaqiX/H9vZV+inq6eBLAbW+w+ua8FV6SJM+VCSKgzAoXWltd+YH9LdDhwRNRbyAbgwl2JIN5uTh2+wT/L/wbL7XiinBud3m9cQk3EV37RV38dhS/SvhrcNwulf+cPhyqt3EamoQvo2V8hoGKIq3Rso+GUNfZiNEcN6ckaiVsEi97rkCExq1KlaaCK2w7X1G5+SRoqnmaWruwKGnbpiszPFzHkxOO0eUWm/4cy4gSmGXWZlf+hapyUnP9XK8UooT8N9qFAmHWYyW2Ncz+hA==,iv:7QlbKNxNXAdhpXH1P4PZBFfMexf3k6DCNp9dOCOsbz8=,tag:q2cxrpg8BdncgyHhDG02uA==,type:str]
    known_hosts: ENC[AES256_GCM,data:1JSnxsvXhraJpsO5JEdsnz//M/lThvjI/a3k26Z/yh2NJetkH73EzS/e3EmvUToSF17krGN9eWTZvRvAfpsfV1j4Oc8vgozx8c+/F7NY5escr8GaMu4JkLwbANlPw5/dQNWIs27gTRg6ywuH2ioRSqTBwgrmlyfGu8x7TYGwzjEbRliySWXgpj93ixWs/+HiaA4jSuoYTkFDeduyKmwg9jb48EbTg2XpXz8c,iv:r13PeVzpQr1fNNnWlWwHQ20zKa3aM5QRetPqeajYkfM=,tag:49C7rTvuL/6axQpDucel6g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaFIrcTMzaG9sS2RnaW9r
            RU10QXgrRE9IeVlFZkJ1a0FuWUNGWkJRUEc0Ckc5TUdnVit2RWhRdGt5SGtWSDIz
            MnY3RU9DZGtzYzI5Z3dRWmJiUFNEQ1EKLS0tIHZvTE9wbUcwelNsYkJZTy9mV3VQ
            RUlXUG81YnFRbUcvakFDTDY0R3NJcFUKx+74PB2HMv/ec5agGRzsvihhcw5t8l2O
            P0J3eHxkiduq1+xiMCgIgYqh+yyCSiXltbYX44ObbmX0esJgL/yTUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:37:07Z"
    mac: ENC[AES256_GCM,data:Z5ALIN43TZ2Uq+yxZXMFq1xVkxlLpN/5sLftwYtM0tkCyign7I3uv92gQ6d3nYQiN4FnlUa/z+vUI0sD7h0eoBUqCs5Fu5rmwgOrh/c/3HN6hAubvZsKNS6n2oBuYzvEBUHOnWJ8o6JDQ4air0jMWOTAb31eRSiAJBzpduyNlwQ=,iv:ZNM9Do0uzz2OcnVRp8EKA5vKSXoWzAZz0L86rF4lYaU=,tag:agY2pnEDVpSxbefhzLpgnA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
