apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bT1pQAPEX/x4kOCJxwexL0FQHYRJ7VYZr/h8r/UfHX4I9evMC3QOiaYm32e8r17AyJWcEDTMqcP7y+RUcFaieuK/2Y/C7fPiGJPpzEEDDDO3Km+bq7eXOL9quL9mnFqFzkbjj9SwjLTdh+3B6Uj9YKx7siQnX/PLrSNL7rFQHLl/f5g40sjcJdnwGaeizvz9S9nh519jox2GtMPtUGKFjZpXg/TXyZ2Ra0q6gtjMTMO+XIWLegCC4PiVCj8nw+cSG0UiEHLBopBxCGo+4Qcm34Jx/KxOAIluCGz9+aFqVFT0hqRZn+o+bsRYpcaUvh5QTSAzbYExWvSgk4T/NHCVz5OW1JwQ2PfDwftwCo1fPcIAn1GBrzRhS3EsJQH6QOYj,iv:kUn2WDNAMQLgzNb81Yn59oDXU1EqyFmoh+i7ZZqBxwE=,tag:izWQzS+vT78PlLYkrmtb/Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:6UhR9oJtfWC49IL542MCce7OfiOssmU0vz7W2kIHwZhAnBPwFA9AG61lXqCtEZFRQn/RtLHhjUGI8DFz3YVFXZSX3+ht8WwdVdZCal+CY0+KjhyxbNlPRKoy7SM/LeZ0LfH7+zkv73pyUPXDCwGdJOxua1FouyJ3fvhbW2QcjjRMKERUarSHlIOhz6MProKyTpl25IBfD0gT11YLyFsBranRPkxFdmeQ1ZCif9+eoBv5zEHMVn5oOdaNjHNnv7xe1J5sz5V8ACsIzD2HCQ==,iv:rNjwIBoAWWcMzj2hrIu1TBfIOQuw3f73a+grELAiAA4=,tag:J95XJ4adTVW+AacbSjd/AQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:NN7ys0hNKlQF8z0VhJ8eiMD7pM+vqkHMAKcr3QyopXL8gIn/lRIkAipIElW/9Ndgh56oES6EVQzwzHni7zjQ7sb17HHz7MxNpZ1Fks5o5F3l6TQRLbTXiXgotOMwkFHd1NxIkxW9vyUreG+Ywe7xWZ2PaCazYrLW9f1+kREhaYE5F83Ql4r3LHAY5ShXs+LNpwYj6YoXEHIOXSZftXINruBTCzn4HVf1PRWj,iv:mrRI30ImTLM/nPJ0Dw0uGQeYzKiYdlVRywLzgrdf3Co=,tag:u2Lyo/qVgIqgJZ4Ojj1K8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jca0kv92mk3n60mwnrf2uwlpsgyt48uz66tudq6g7ud5uuar84tsq8s49a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRjZ3UklLRmI4Ly94VW5L
            OEUzZVdqT0Y0Z0swQUtPMlZ3QmIrcUJQU1ZJCkkvdmpXMHEwWHZoR2JEZlg2aVQr
            Y2xiU21leG5yMkU0Q0hrQXZiblM0RkUKLS0tIE9mRzhpbTJ5d3ovdG5qYTc5VFN0
            d2llc2JNZE45cHZsUXdNKy9wdTlvWE0KsR2WBakU3gvfGOvl5WGAUuenQBB6mx36
            z66KjiTPYLs1d8E5w1EtqJd1GLe5n62OGelWidVbPjt/zXODXtD7YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T23:05:18Z"
    mac: ENC[AES256_GCM,data:U7JNB3U4/cTKkJhWVec50hnfBR4A6lxcRfHYwnzJ6UN+DUGUa3lIXLUadOMGk/pNL9vkHoc80ufnY5NDW7EYzsH51ApK+pAqPgYlGl2936bPwk4eSKYEOntQxtS4j56EgmmuCN5ZV4+8ytAU8JJmm0bPN51fAxAtA8BJlmr6Rr4=,iv:p0S1A7XU6nLg+uGe/8CyNRygwj9J92aiKLMS1ove2tE=,tag:1f2XBeQvAcZlHyALLyZx2g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
