apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MH9SWESJEj05hkJA01CZOIuIqCQTkHV8wbhaEQ9tn1OdUNSZD1BdqKurbg8AcquvU+iFzEkoulBE91tWsTA3i083N9ReIrQVpk8vQGvy0geLy4kHChKo1ZVgqevt4Pzfjc68thwFVxPIsGvkFIi9w3kSsXPq9ZbEslmOsUt8uCE8qTWx4Fy4P75CZ+8kww6pMDWvn6P8D/FWjy5IH/9rCO15h6nPRbiu1usiFnrlhV8Qinci5H3iDV+z1XqNaGUGk5JqC7XQ7iPe95MaQeUf0p8wesb6heVlVZzlT8HWjhcw+9AvpKK7bN5EprFRwXJtSrrlRDxDu+urhmcQaZg6HIlIZPGj7NGJw0P2Wv0ip1MZ6TUyusVhvwg6tRRGbPY6,iv:bg14HJ61W6Zhhk2ZHmpEa3FNvkFSNB0TeLgTNLVC5oY=,tag:S0i7D95euYkdEQozXCDmEQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:aiHiJjtjJJeU3QwzrVNESzFpSTFDPOLi6rA5mWspYnTVYEW/to4bJ2cmqpTwKd7lRSxeLu0ChUZaZD95xB1IJ7Q+p9aNbbCu6RMJ/4uLClmxiT+6VTDavEER+/4gxo+omi7WG6A36AUXcyzSiiWUQLQEyWIlXaKTNSGaihLy3Lakf53vxcpFyCyp9dAfcN5ob3DAC6aLKJXisgWHhLh2dLsXCzOoEE2KzZZR5/+MsHvk3fC+skT9uI4USluqbcqZ+OEdzpKNUfo7liLZPA==,iv:fUywdmaIWDZQS4vWrqRMspSTxJBpx8dgW0iwyWM0EPw=,tag:q6ybql6/idASo+8tZIKZUQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:i6ISQTAuO/WAWaZ8Oo2CinS4rTC4ppP4k5Q3S/ltL/b2rwbhajAuma50rIauZPk9myqdpaJTlYy0vxV8xyYZDBUSGUlB/+FCty+8tuR2QiHGfGQcM73fnVKIyF5LD1QeiLMdou2Ry+78DY5IKRIMdjUPB6M+dyRop81OfKvIh4xVsx9uRGncLddneAaFtS6HE4lwRHIhirDB1T8B9B2XNYRCOt4doke5lQ7S,iv:STa4Ly7j1iF0ZRBkN/KYiN33qbqpB1IzIsvDPasCfU0=,tag:hiNgOGMvn5BURfuHMeCkjw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdTJxdkJ3cDFOY3BRS200
            dXhxc0VUaER5Z2I2ZnhMbTI1eTFtV2ppUVV3Cld5SzFUUVdDNW44eEFzMUgrbHhZ
            UkZxU1A3eFZuRW5iM3pWWUs1TmdNUk0KLS0tIDBxVkpDdmFKOXVBL2FtN2hNQThz
            TldKOW13cldqRTdmdWNpQ0N1ZjFYaUEKtnXt8W0DuWQuUEgWdImyTEzpnWVaFi0d
            +BLNMF2NXI6DP17x3LdHlgek5FWYgsF/s4npL4Hw3ST3Ftqylbuxtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T23:39:33Z"
    mac: ENC[AES256_GCM,data:/AeqaZd0GDfaX0cFLrgAdEzTSG9gqUzu5fl2bumlJd0bziDtIyCnqRTxEIQS9dIa/Y8Aw8LEfXWuhaH/kBJT13pVaYGg/5irsjhzHTUrZUcX2+UE29pPxj4kFN3TXYlBrNJi8u7NHYVjbJH3Ug883v0/VOhihHLN6bepAlGHoo8=,iv:G5SsowAQ4I2eyTD4sKBwjYGD7Vl+aKV3JSXxq6wTklo=,tag:jvgTLK0JzjXEOqfE+lgmHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
