apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TPZDLZ9G1hz2GbM9uTJDF5Dl6q6W7GxdQTIHofmm6Fps+O3+9Fcgcuzi95jvD24145MMYo8jmtBEg3x0lgBCIQF3BjGmQMxtunmayASBtJaH0YB/O6XJrKuyvWe8n00p6XOCscGQpkg5ii8/u+fhKmxI9Dk22PJfWIsd8HjaI2FLq68Ns7FrNfv0oGw0C/WdeAwMwfG3F3rzuszxnVV+PHDOEKT6KueVTmviSMzmzPWTz+NeR45legRWyvWk+2R6V7JerSHceuwJhZOXVE7XsOGL05KIvlnKzJUlCDuFpmFpP2+RMybmXfKD/l1E2wJ3zvWFjxpPMId53ABmcwwxKhsZ6Tp8y4df7zekrUDZ/jWePldWNaYQg9Xce2nWisix,iv:hW6qvvC3I1u2BY5MFDK/qE0QyW77qXOqKSA3XZLUhFs=,tag:yE1OO/zBE7RT9NfsL+qskQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Pr/mpTHDVRm6eTdA1gtQi9ATe9sXFgOBjRa6/UX4VtS/lzzFupk1l/vzKezp1YTEK1jbpKAaoihyttS+QJ9mLMT0o4uC8AceXJV7PfC2eZltrR/iee4kJYAT5fTvtmF1oPrfxNOkg/srR2EpbsxIZpKStsMAcAisTPDG6yG4X+Pu7FegtbD6TpNCek0Scf1Qje5Hb0zRE8kttUkjwcouubAht1B8+TC/oxNMXJRSRdKOy4UHI28F6YoFLiGOsyKb2I/Pge/VJVRUyueZFA==,iv:o41EP11saB37U/bB0BDq5BasIbJvXxKwtATYFLtZ+yg=,tag:6r6MAAaQWpa+PM31HX5xDQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Qsw2EcxBdV/7ug1vlm6eSiINSm3v6XxSTVguAi3VibWvEBnmZ0OhKzgx7a7U2oJ34IQxiHb0pz/QUvJZwe7imSITnqnNAzlWIJG3NSfGCp7h8a3UPvsz9KHdr10eU/2JnAmrFJs72kW8F+MFu6z1DVw1aXtCckBlmevokd373d7Xb4ghBkNxXNjQv3rf2JJOxuMi6f1euW/yH+e9glkdis96MVpFVr0uzk9a,iv:SzGN5F1AphUZdKPuGMv21DWLFlvk1Dn42chqykWhPwY=,tag:lSyWGP4BG/IopLtp4TtTlQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R0dWSWVzVEhINS9JYWkr
            aFcwdFgzVTBsR3kzd0h5SVpUQ2x6Ykl5TXpvCjV2TloyWFJsOUcrd1FFMW13QXN0
            UDVrbUtwL3NoL3dGaVNOT2dzZlk2WU0KLS0tIHRBL2daNTE0T1FDYkErQUV4QUdT
            NityVEhodWd6Um0wMXRVQmFmLzU5bE0KTD/b1ewXyk7ablsiHz8zTQ4HpIv/XQw4
            z7CVj8o7JGdj4ds0PIQzVuykMG8AC2vR2iIbAT+zhu4K9t2kAKdcgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T00:05:56Z"
    mac: ENC[AES256_GCM,data:K6ao9dpYdjc2F2dQai7A3UAcEdnlZUUD63wiyCWnhKk9U3A1Dt6/onjgg0X9kan+q5u6UV3na868LNGlyvIbKFoZZvCIAbhotvBotswL28myAR3xT6KaKDK7/UFNPTmEVIqbJnUUP+tkBlTnqCGw+45IdD3n5312c3LRpR41Xy4=,iv:+cPofA2xj8nGyNt4T2EyjTzEDYdQIC2t1Eb00skOYyA=,tag:ZkGWaO/NhtJmDu1KIb37gw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
