apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:egGdOJXzLpevGf5jdOO1FI1kmMT4nF1J54J1wKdQnMdTOANYAXza9aaVEO5GRnmxEwmwhKaQFvQv85HAzlxQiO3dgxjc8VD2M2pCG78hLLLvK6LoB5ycdmp6BPIPyncQIGF1ydRH2nl2A6LUwqi1FvTpG4+7SVTbbsirAeeme5k0OLXcXW5g6Ojm+J0Keue8/ghwOvxfbjdQGC76bLY8+I85pj5MCGxKADYT1wfGbTTPzEyu0NXpp3T/mB+FFUKyfDU1hmjePu9W0GVul301doqLuVZxLjDCWITLzaSpRhF9hoPpla5AZHmzcrLSvs3lMJW9P+RJDPTnOSdq5igrcw6FeeKkECfQO8V1ElN0T8dof8THWd3DulZuwbNPU17y,iv:0zUOTSUjk42mVu40Uww+SPMbwYlc2x2I7pUd3hl1Rgo=,tag:+JGQ6KGDCG+K3UKY/hG8/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:MLWWKBTr0wbpzpe+WcUtNFe2uRJv2zLeuaVre2xK6uvbusNCxE+HPdYwFOQSwBTA1aZHA7eevscESAq5cg63dWQf19wJdTDnSNVBzUonhFg/YgreDLOoHw9bJOYD3z7j9nRy8MfJ11eyi2VTg5/iXLg9avYGB9htXI4rYLBvM8T57jc4qoj7m41+0RHiKn8SRqG1nEoTWakNvjHZftM/m2qUyJfG6vN0G09LlZO7afSDaGtNC4uvRfmu0+L7zk4XluMEmW1NZQMYYvj4OA==,iv:Xqx7z7h/DvacvijdVsiXHViw0dORiGzyU0nHCCrJs/Y=,tag:/kWP1AwlvCGN6qTg2+rHFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ULiZN+s/hO/vHRGWNmCrh3qqFA1ohAMcM/jNr4n1u1sbiuaUSzsQlcwrR0OOyGnb1h9CkZj4M6EqnX+GSmYZfEtwdhproKC7SwymAZXbGEyRnzk/XbLZiBETpfeu1DjDImIfN1CTuG5vc7PlSE9hMGNtOz1Zt3u2ZOPQ9Pw7sdiGec4GxWo4STqoTfoaKh7rzRvGvVKdz1uHuRRbH7q9BN92uCPc9eBaj67+,iv:p8Iq2anuRcii8nrvVPZg1hqu0gUnOEkjSs0C5UovzRs=,tag:Qq3iI0fIVqiYEo11yP8GBg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVjlBd1ZWT3ZqT3pzWmpL
            c0dIalZhVkIySFBLR3lUczRiRm9CNkIwUjEwCm8zb2xaNGliYXQycUdZWGk1TW02
            Rm9iRnBiY0dHQ1phTVpjQXQ5Yms1R2sKLS0tIEVWYTBqellrZFdua054SDdwWWIv
            OWVlYUVIMmhoWXVrV3NRVkVSOFZLWncK5XxcFAJO9iSLfXQdq9ivBwr/Nqa33jhU
            ZK8QVvoA9m4C4RWn4p0nnFZBkzGPgA9vaCsr6StS7WR1nbwb5ksGeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T15:56:33Z"
    mac: ENC[AES256_GCM,data:3OAyaZ6ZGubqBWBYy4kew84e18Taz5Vlt950A5gGB/HkktU4+MkzmZtixwTZYqar7wREQWOczPOTcdUuInvWlcJ6scu4D2qWo8QI/VHVFbZlnLhR/J660rCmZLcGrRYQ2h+LRtGaNC8svtX83FNrR1seV7RLSV4pWfrCM4cUv3Q=,iv:wj8iBz+0UQf5c3loaoC9CqMqE6KlHI6wt0QhjzUztqk=,tag:LikHW0XEcdZU3AWuFQlTyQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
