apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/XYnXxWpAFpCSfLdCQf7e9Paa0hgAjnenrn+EgH3RCZnb8q3smGALVmTnMgIRKZ96z6NwzkdCY5GUfOG91pDb1mEPmBf64bsvCvEaR8Bc4ZwRS7eegGa0YFgc5In7GmEMzDjVblTCSQ470sa8Njm/+gfqGmrx+tEmGOHYjKVqGoqDNz2VV7vfZUUgsSiDDYIB+8CDDYMbMI0Yjwyq9He0Y3jvyGqW1OpMNQezawl3bm4c5u7jQh8Jfyiw6UhHL75UyaGLxUkPAM3/n4qSk6dIBAUtFO6QW7u4X91Sgsuc1EaMiM+mKgZKDP/emdoBUi2xRwHZBk+ovL9P+bVl4inck0jZFEwmwoKB3ToMt303X1iFPkXJlwCKw2q9lHprpHc,iv:wzZetIgv6JvTSA5TRQLB7UJg5tko/jNX+QpPg63yNAA=,tag:MR/MI6laRm66ldVFVec/Yg==,type:str]
    identity.pub: ENC[AES256_GCM,data:pI4EfMIbzKTydfQKIoFHZ8yCuyX3NmTqaL9wez0OLruxH3qwwKpBynks9HiZt+BTcTmGws6+aqJGGzXM1R4TQBD2iQsTjl5SV2yU0lttpxLlPez9uV1GJgtHYpJYFYk8wQ5W0iDSORjMnK5PKwEnwDT6e6CJJXZKS1KcxGP4T8KYim5KiozD+7vr8d7vM4CEGqSnSlL0PJ+wxkb08AHCuEanvWsEiJ4Q5MIMc8iVQsCz/dq1CoVVHcV/74/1mL2/jKpivx5GjniELfJNzg==,iv:6vIf55GsaH6HsepnXxDnUSFMiS7HYgZ0OhOgOuHDbOo=,tag:hctqEAGGBHRhCvUz8+WbRA==,type:str]
    known_hosts: ENC[AES256_GCM,data:l84icTa6plWCNK4M7S56tLVXhpRn6x/tnB9glmBXXGlUItjIBKJS056udjtdMeOr/uxoA3efBMWPYHvQ26EBdPFoWfJX7I0hdtoD+VEDZff4VkYPcbMKz/FmM7ektd2YSD4ra31hbC9iSnbQJq76pEDgTBJh+/rhITt4JyQo5q3gddY2FbpplAJZpPkkYs6XSmzlhUsymeprb/4REK5QP1ZEaP2ROOc3sipC,iv:UmfvAJLMlNtF8WShFfuk78RRcPbocTFBKLR30UBiILY=,tag:mdC0vygUEvMzEY94O9hsuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z2pZSytjYkQxVnVSSkRK
            WWVCdVpIbDE0eU1tM0UrN1VIam94VXhzWUNRCjBuUzlRY1d5YUVjNkgyRm9TRW9m
            VUVLYU1IbExnOXFUTEg3WGUwVzlmT28KLS0tIGdSaEU2VEhqbS9zNmNBNWVaYTlR
            SktJMWVJUFFKYzVvczlJYTZoTXM4REUK334Ief9Ot5B1XAxX9VEEq7Nr38aG5o6r
            K4Qwn/E5EjylJl2iRXNfPMFTt/BhmcT8rVE4l/KauWQAXLca+/ZlAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T01:13:11Z"
    mac: ENC[AES256_GCM,data:ipAXqdbYewyPIRbTx2XnzrqB5uaMp4WlKwK3NkSytJxXOxQGVdGrgdWELmpQ+zi/yt2tazNt5xtCP86qOvty8eo9tbGvd0Nk2L0Mr1vAhfIt9RUJEhfNb+hE0Kh6SU1Q+0pYzlgrr7zOMGZn3TMCFKk1DpPsEVKy0VcgQ5J97yg=,iv:n2XJ7rjU1olTm//ZYJPFej2yw5nPC4XDzJ0dBxZwvIo=,tag:GDPYflpo+KbqNVU6R80O1A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
