apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nVyYu4Xo4UGvi4TfxB7WA3DDnL6b//21c22+bMX965b7KfhgZ1yWH3/omg1LKauQVQBEBUgAghJXNB8kErZ/Sia4Mr32GQ70j1d6UvUf5fWZEK/Cc2LC8X1g4dQqEerQGCqX13ea3AngoTTM81lR84KwX3HETP0NfurRwq8h8EzM+134RaAGfeiiSVXNync9Qdhpg32B31Ef5Y/u9hnCESJ503ZftVZ+1V4J9xTVTcZAaPp9NO9C2eATNV8kcqNXdooay2AfXfD5Vg62GINHOdMPErLmauAjtHjhEnk3ktxFD/7uiglQg7yLbuKDb5m533HvnWMZYhODKU0dj/lP2bPR/nHkXksD30qrt9y+Ep/MGWBYfdlwcXrTQQiQQvf5,iv:7kWkBYdA54ZbiBvd/ZmMeS5nadXDkcME73v1/Bn4le0=,tag:kTHLQ0CTGnrTc9Jonw/mIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:EQMYJqTbeCDGOpEd68pTZBlM/c9NG+HSkYws+reWx3zMQLZl/mgqGtc9Sl8/DRm/t4MiB6VUgzz7klStlRsT3Pec/xjFocz6+/d2POwQTVpyTynaTxW6y93Pyk99S0HtShanATJzTsxO+1ywFCgdrLBNI0OagKc3G8Im05kR0K6REDdI3h68qpYseeSb0sb3dK0VzM5g6bZuQT2mzcFnGW21uA9VlHITNPZSiYVxDz9w2Bl79JnsG754boFMHv2VVSr6rsjEsrUaF9oNtg==,iv:7lhED99V77N9fEeYAJla8/y2P2yHA23UBsX1QwsDGpw=,tag:YZ18pc580PDMmtPYozSRBQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZPacxq9ufKWQjPENDGlZZUA2QqlqoiBziZTlC9bFZVyPXg1AnkddBIqh2PIJNQSWExsze8iePzwhdnfdwxNIhEGOsbPz+sVgmrEJOAQcM4BcRySpYM5LlYNY+vdiiexOSva4LCAX7MMA10iIo7ykwQW8NDE+aRscZ8uni0Kht4+by2Ip9NLPvZXhs9HcflwWSP9XLK1dV2yDu0MKDfzDTiR/vHN0Z/uZ46IU,iv:uXrDdm8Vm56Q0ubPJ/04e3L2zeK+2A2bCgsVG4UVcxo=,tag:zH+VSvXl6u07QAGvZ1qXUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jca0kv92mk3n60mwnrf2uwlpsgyt48uz66tudq6g7ud5uuar84tsq8s49a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVFlpODM4QnRmUXovcTlk
            Ti90bzdDV1RvemZtY04vanFjOFNMYnlTN1U4CllRb2ltZldFeGt2THlyalhZbjM0
            Smh1U1paeG82UzV6N2xnMWhadlo4YzQKLS0tIElxVXhSYWR1bWsyazA2bVkyM2l2
            ZE5Qd0dUTkpUUmdjOGNtSHVmOG9EdDAKgxOhMf4eOK7vmQbFT8oOYqHI3lpVUOEl
            UCw9+dLW7FNuGW35UnuBHixHrcAgcoicTwwSYBbWC1Te4JFDSXXgaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T16:44:04Z"
    mac: ENC[AES256_GCM,data:1d8vvZSL5vVGjSgqyjl8VOAjNjeakLzG+RvHbb5aDudGZf4F9WEUGakJUAN/wjRwti0AU8kL4jQvj7jEW9qAwJMC1Ri0MYey4xsEqEHo0xAZDFxdRbXt9Se0IryPAGx9x08AZ2K1Kt43yLgvQHQtdC7MEL1b9eIY0VEuAcy0S8g=,iv:/VjayhuhlwoUHOKd0fC1x2yOMjwjWQ3bkBcabsQxByk=,tag:7MZpJW1c4Z4fubmIpT2ctA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
