apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mIqWrmtQ1VWanBpTI8o+xoIhtXHiOx/N3bZC6f9H1NpE8YNeet+VVFPWdodEiO3oKQrHZ2sy6psoOQzKKRlA33h48kmiXcEoGNehtDlQ5vTl5Wugun0S5kf2FFwEwcwY87xgAM8flEdDHX+ijj+/vAoy9PFdRr/UJKOz1yFf9ravf9Z6CpiSKzVHC6ReXn9RtIlv7bVJpk033dd2JTdhRRkWTE+enZR/7aWzYX9r/86fSoyNyjUeLfRydcVaLK94GFJeaHWa2F6GEm3YUiIDJ/DCdk6IXCgP9eMotzg0ZfLfxdxdIpLovoaANMEFXIQqtoBCtBMmJG/X9bmR8+IohpOXUpO0lMhXzMkazA1x2FZZrTKzvmmxtImeCZi0cgQK,iv:dLln2QxV4UGy+g3HzuBeU0V3L/iLHQA8QLv8KVfsTLU=,tag:VknurQNRXIKn5OYVtYd1gA==,type:str]
    identity.pub: ENC[AES256_GCM,data:qMJHv2RuBqwYJi2/x3N5Y/A6vrYfnKECKo6vXy20txJu5VUWIboyXXX1G65JABc9AfiRleuZg3lPcb/0xW8d1TU/tQ+kERlcXRujQGM5Z3TxTegkti5UBsoo5sWyfFd9s5HzgB7PmrPt/b/uqKs+WgsClYxYPdrMt/ibylTIbl/B8WIygEj604MVEn+mYDHp1c55YK9O4+C36DtFdLKafJLEqTFty0VvrOR0ihuckVIx3wXULn7DpbHUbsdS3T385bJ0sclz30/6Qf1d2A==,iv:WIPvwVXzjrFmNc5bZZug5j5+HKsRrozdWnhXd++aWvw=,tag:6n9Bpi/d2IhcxKmrmLjI0g==,type:str]
    known_hosts: ENC[AES256_GCM,data:xt0O4/guxatAfj2vHuDGYznHdrtOjPBbaZjXugm5RasGlj2xu1bIMS2kvO1GVxfmbtaz1/gvfM+/J6ooCg2YIe/kWkUNsZHVRwY/Rrt1UJKARu4FUTYghLky8VaaT/boxxYqmp0jSBQndsQ5rbHtkxIa3+tNliOlIEQw0iILYC4tWpnIz+fVcqrBlYAOCqbYAmoUDNbgqbxB23qLOtnbu0s864CZMxNyXAAy,iv:hbTbGc4gXpzOK8O5YEqPEALpY8cwAodpk8ZfpZSIysk=,tag:aWnHHxCbhC31P4RA28qcyA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV0xEbG14S1ZoTEs4TFVK
            bkgvNXY2ZllDL1dpU1FweVlhMXl5TEd4bXhNClhiU0Q3TXZ4UDRoN2RFU0lqWkdC
            VUk0cW9CVmltQXRDKzN6RSsxSWJTbjgKLS0tIEhpdFRROWNFcjBXUW5yeWwySmhM
            MTJKanA4WWtJamhvc09BVC82RkpkYjQKULkWRNn1bLWwJj6Fiv86VbxygoYlGvSn
            6Ilb6SU0h38X8jSAh4y6jIgKeihpdk/uD6cY6BfakI6+hWUM9ceWvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T14:57:21Z"
    mac: ENC[AES256_GCM,data:GwZSmTnEEWBBsJW/bbWXIt93AWsQLOrxjEtEnUshBu4eyb6d/jFuR19iev2gJrODZ38GgUVLlRGdPmVh9FUwYOi84uGqp6Yua6gkNO0fN0vHpEM4hJCEIvLpF955KJeNU/uerkPDfuhuqo7a870u0Os7Wq9QKwosWPoFcstN/ms=,iv:74lHU6umsNMyKVuVZl5fzpe+t+oFwKjuNQ5bG61HnqA=,tag:o3piXVm6NHfDO5pNkd6q2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
