apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HETDkTvTrQF8F1lzYOE2nBIrHdb0Nvb0bN7i4SwkdsmU6OhKtS6MqfesfGOk5+yYfKaWAXHj1qyz0rs9jIHb3iZTIocunNh7O/G4NyOFLBy5mLdJw9GX38gJYyYj/mt9/YGbroBDRocC0ZL8+QnWqQOpuZfzM5z6rh7uscxIjkvf2t32/ybTcSQA+IS5cpDAdw54TpKABwy0i1EtNEXterpQmnT5PiZI/6RwZJ0oOv7fFafLnSG/ytNNimZvfsOrEEK2Y0kL1W01sxeIr3eDr0VwKFoq/MrsYJ5j5/QVfSXWNz5wTm+zDdG/awipqGHDdzkVUjY5FZCz0R17ScqLcS6/KhWEM2cl4ce7s5aujFdlc7eC5Y6t2e/GKc0tTgMz,iv:jzj3/J+L+eZN6bN7Dhu//Sqxze/H94ACuvnnM5puF6Q=,tag:4ucezea8MeZeJq6sPIsCKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vd0X0ZvjDi2PPFCT5KcUyK2lCOIMC8SpdiwaNdxaas9iGXLRDv0efx2GOYLnaE9vrpkIOu9h11R2BsjPjQqkUp8G5uVNe788BYLHwkg/7MnAy5lWLcwCGUfZv2gLq50Qtli4T/MoXx3DTLYcmHkaZiQAf46qMipaj35HD73bWHvfgNZdvSIpeJs8tDVtp8gSWwSAxtlG5qgs3q6E43lHQxJmiVHb6ld814UfpJLHGcJfANVyiSKfmiXMK23ftoYwW0+uihwvWQJ7fwB5Cg==,iv:+nFcCs/lLBJgdE4ry7YrYziGH273hJEAQqMq83uxcxM=,tag:bsxUQ2fcgXbyvetXzTNtFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:u/7e7P/jJEikhojfTa2CWWoje3VbHOwcuMm28KavUkMXKq2OO4qqeqYrTTF0ns+KIuLU6ydi3txhkEqNfC4VNjSKKVM+YCEgu9/2qJwnczDtfQJgaGF0sCGBwLm+gf+dyua0/XVjV7VCnUqkhWPbj4GRmr3HaKId9f2Kfb35YATCMmzABRz3fY7mnXDb5KhADLxMPocqCMHFQGZTjCW2u6k3X3Ykq2ky71aP,iv:6Zkrspd6RT1oY+Kza5B+fFeai7Ma5npFxDWEBbkPD0g=,tag:gYNfHqed0vUIpXTVw5uzng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lp9h60auc6723jamz52cg3a0ecc8g00aynpnjl9z7r92q552g9pspnrelv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzlpcUJQK3JtYzRQdlNh
            Zk5EeXczZGw0c3pwdUludytXVGpGcThyZXd3ClFQOElhQ0k0UnpqOUs3VmxaMnBR
            VmFyTmU3aXo4VWxTSkJtcEo1M3IycGcKLS0tIFhmVHR4NUpDRjFGR2RqVXQzWmlD
            M2xNTUNoVC9FUkpaeHZza0pvOFJmYzAKAuHlI7En1jf0qAJTTHc9ulpSvAhX/vSy
            rZaxMA6R6dH6VoPOKm0qv5teVlWWaDY7Jxxcl1mavS74DsHGD6Tijg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:33:23Z"
    mac: ENC[AES256_GCM,data:m91LkgLRQ6084YXn/xhtpoksy4oZlT3bCyqL1hLoYWC92HFWtxo6D9CuEpVvX0aC4knr3IW7eCnd+EcDLuE4QCsw+4iWFthqB6uV5C75DIZ5J8USoMqsRs6UPn9Gj/6EkNFzn5RukFV2e6EWxaIAHO55magGYcSxfAU+nkunCFw=,iv:JP0gjyh7fptZLp2QH//wet1WYGHjhsa1Gbi72/i3mSw=,tag:jprgvwkI3VMegnoehDLlDg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
