apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PRqWqMuyEyZGDMDrWKpubqxMJMPYErDhOvq8CrMKoXdXBAJyh5LuYQRtZxkskQLEMhdTyqEV5JtCmiwxt+EDj2jfynGsO7Y47A8o5+W4Oa8AOob7MBkU4bcp4r+PAsekxFbvTnaE8+R9Ir1coCZhFYRlmuS7VgxgHuJ1oQDXcNJMSSaxfvcuUtsmpKeaIWvjTEAzW+nMJu6QNZwIr+XiWVL6r50FzccOThc99Kt2dCptc88omxcPuJl95fn9Tf7pvcO68B0oL84F0Cq2ECau8VxzNC4k7ZgdiGVv4QWua9PxvALK0OSZ/AzNkCH5W5clvYM53YvSTpSmXz+CZDElMNYiRA+Iujrq6AaSmgfdD1A39z+RA1rZw94ePWzPDDBy,iv:YbSNASUozE6JwMTCOa9BN52BD7ZGxFjmxDXwQMUZF4s=,tag:3ysueqj9opmJcM82+rvXKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ozeF7JMNmeDgiw+SG8QfDAZVxbcjMZlnANW4RDMHEk1fGl6JqwNAnp6IBYkS0wMtB3p+X+utwHYgb/5qKCRYzOEx/i0qzTuTS8qo7dVaCVvpFe/ctsL3xaaSjqgnV1QdfLqZz57H+yn4uKzJNk5e0WE5sXgHxg4LHK21CsrYODodvgVxF6zLFFwGunE8bo1fMT/8A6NVLVSUw6ESBdirKT3w17guszW62F/4vvNjF8Z8l9V/a5pG6JvMyHc7OvJglX6XPTdlO9JxEd06Jg==,iv:l0NpV81ggY9BTTXb7yzYu88u6TbnMx+48t89LzWq+RE=,tag:J32u5zBw35jeqY5WeLRK3A==,type:str]
    known_hosts: ENC[AES256_GCM,data:FfyrHv2DwauGQ3I/CeQynEnKL1k8hBgWHn/1SwzlU0Uv8t6VEh2EkCGrS9Y6t88pw0C0JIQcze1/AAYjomidf+3lobgcjNt2/aHjNtg6OjnbxVncFUZ1H0womaLMlrle5KhPWYPCb5WZo6pFN0jBNbZEpILlxFlk96ZMHo7mL3DJBqJDYS4nfH7CDcuwjBB1bNeq3JAzaTZBxnaISA8TA9Ur2fndtcFx6mAD,iv:+UYEBrDVKlNq+Q9rMAsQKaA8bqfS8Mo4iqr28ZA7kR0=,tag:fZvit4iAHSQ9L5r7uO6jfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jca0kv92mk3n60mwnrf2uwlpsgyt48uz66tudq6g7ud5uuar84tsq8s49a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMTQ1Smk2Zy9tNDFqSDM2
            cjZjMGMrb1BVb0lETWpEQnpQTXZjVmt5MkE0CjJXS1JsalZUYytDRi9KL2VvUkdw
            TTY1TWMyVURSUDNmdGpsWmdudnVFazQKLS0tIG1tMkZ2aFgrbmJaOVJrVkJLbUNu
            M3k0SDcrWStLMmtraGxnbmlEUWlRRE0KjC1T1PEnedBdCbGx7+TNVgi7/GU79PTF
            64LOEWG2EmCnAOCzSo5s2VYu/HywOJxVuSn9b7RAdDXsNp9Fb/O82g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T19:17:53Z"
    mac: ENC[AES256_GCM,data:y4DtyWOEAF1JAVnlvtXmzLs9ksO74AyIVuzMwYhxvXyQ7S4+sFKUK0HsJWUUCkt6/mIFr6/D/Xy8uwkBrFyXud+ERAZOcY7cPhqyCSQoji2i0x/wCUCqh45Fb3Q+Mu7WS3ldCvKGAzum4QvpG9us9LT08Tsrsi/e6t71fvLjCLk=,iv:BgtO6Gtk6keUUj+mWkJlp++gvPj0d7PrBXzreblyPbk=,tag:YNATY9yVy8S9SUmqDYNTbA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
