---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: web-grab-plus
  namespace: web-grab-plus
spec:
  interval: 15m
  chart:
    spec:
      chart: webgrabplus
      version: 11.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago
    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false
    persistence:
      varrun:
        enabled: true
      config:
        enabled: true
        mountPath: "/config"
      data:
        enabled: true
        mountPath: "/data"
    portal:
      open:
        enabled: false
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false    