---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xepg
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    image:
      repository: docker.io/bitnami/nginx
      tag: latest
    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-xepg"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${WEB_IP}
        ports:
          main:
            protocol: http
            port: 80
    persistence:
      config:
        enabled: true
        mountPath: "/bitnami/nginx/conf"
        type: configMap
        name: nginx-php-config
        subPath: nginx.conf
        volsync:
        - name: config
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 0 23 * * *         
      www:
        enabled: true
        type: emptyDir
        mountPath: "/app"
        volsync:
        - name: www
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 0 23 * * *